import type { Dict } from './types';
import { ko } from './ko';

// English copy is an automatic translation draft — native review recommended before launch.
export const en: Dict = {
  meta: {
    title: 'SOLKERN | From Origin to New Value — Natural foods & ingredient R&D from Uzbekistan and Türkiye',
    description:
      'SOLKERN introduces the natural food brands ERMÁK and ASIL from Uzbekistan and Türkiye to Asian markets, and transforms fruit raw materials and by-products into new ingredients with Korean processing technology.',
  },
  nav: ko.nav,
  common: {
    more: 'Learn more', contact: 'Contact us', catalog: 'Request catalog', b2b: 'B2B inquiry',
    viewProducts: 'Explore ERMÁK products', viewMaterial: 'Ingredients & B2B', scroll: 'SCROLL', langLabel: 'Language',
    readMore: 'Read more', back: 'Back to list', send: 'Send', sending: 'Sending…', sent: 'Sent',
    error: 'Failed to send. Please try again later.', required: 'required', officialDistributor: 'Official Asia Co-expansion Partner of ERMÁK',
  },
  home: {
    hero: {
      eyebrow: 'Quality Without Borders · Official Asia Co-expansion Partner of ERMÁK · Ingredient R&D',
      title: 'From Origin', titleAccent: 'to New Value',
      body: 'Fruit grown under the Uzbek sun meets the Asian table — and, through Korean technology, becomes value once again.',
      cta1: 'Explore ERMÁK products', cta2: 'Ingredients & B2B',
    },
    journey: {
      eyebrow: 'THE SOLKERN WAY',
      title: 'We discover good ingredients, build markets, and bring what remains back to life.',
      steps: [
        { key: 'origin', label: '01 ORIGIN', title: 'The land that grows it', body: 'Strong sun, a continental climate and a long orchard culture. The fruits and nuts of Uzbekistan and Türkiye begin with a story.' },
        { key: 'product', label: '02 PRODUCT', title: 'ERMÁK finished goods', body: 'Juices, jams, nut butters, seeds, qurt and nut bars from ERMÁK, made since 1992 — introduced to Asia by SOLKERN.' },
        { key: 'second', label: '03 SECOND LIFE', title: 'Value beyond the factory', body: 'Peels, seeds and pomace left after production become food, beauty and industrial ingredients through Korean processing.' },
        { key: 'market', label: '04 MARKET', title: 'Asia distribution & B2B', body: 'Finished-goods distribution, ingredient supply, OEM/ODM. From Korea, we build markets with partners across Asia.' },
      ],
    },
    land: {
      eyebrow: '02 · THE LAND', title: 'Why Central Asia, Why Uzbekistan',
      body: 'Intense sunlight, a continental climate and centuries of orchard culture grow a remarkable range of fruits and nuts. Good products start with good ingredients.',
      facts: [
        { value: '300+', label: 'Sunny days a year (regional estimate)' },
        { value: '1992', label: 'ERMÁK founded' },
        { value: '2', label: 'Core origins — Uzbekistan · Türkiye' },
        { value: '9', label: 'ERMÁK product categories' },
      ],
      cta: 'Read the origin story',
    },
    fruit: {
      eyebrow: '03 · THE FRUIT', title: 'One Origin, Many Possibilities',
      body: 'Pomegranate, apricot, cherry, apple, grape, nuts. One ingredient extends into both products and materials.',
      items: [
        { name: 'Pomegranate', product: 'Juice · jam · sauce', material: 'Peel extract · seed powder', image: '/images/fruits/pomegranate.webp' },
        { name: 'Apple', product: 'Juice · puree', material: 'Pomace fiber', image: '/images/fruits/apple.webp' },
        { name: 'Cherry', product: 'Juice · jam · sauce', material: 'Seed scrub powder', image: '/images/fruits/cherry.webp' },
        { name: 'Apricot', product: 'QOQI · Challpak · nectar · jam', material: 'Seed & peel materials', placeholder: 'FRUIT-APRICOT' },
        { name: 'Nuts & seeds', product: 'Nut butter · bars · roasted', material: 'Nut by-product food ingredients', placeholder: 'FRUIT-NUTS' },
        { name: 'Grape · date', product: 'Jam · confiture', material: 'Grape seed · peel materials', placeholder: 'FRUIT-GRAPE' },
      ],
      cta: 'See possibilities by fruit',
    },
    collection: { eyebrow: '04 · ERMÁK COLLECTION', title: 'The Taste You Trust', body: 'Juices & nectars, nut butters, jams & sauces, seeds & nuts, qurt and nut bars — the signature ERMÁK range.', cta: 'Request product catalog' },
    featured: { eyebrow: '05 · FEATURED PRODUCTS', title: 'Korea Launch Priority', body: 'The Korean launch proceeds in phases, starting with channel-fit items: seeds & nuts, jams & pastes, juices and qurt.', cta: 'B2B inquiry', tags: ['Online test SKUs', 'Warehouse-club bulk', 'Food service & bakery B2B', 'Small-pack convenience'] },
    secondLife: {
      eyebrow: '06 · SECOND LIFE', title: 'Nothing Ends at the Factory',
      body: 'The value of an ingredient does not end when production does. Peels, seeds and pomace become new materials through Korean processing technology.',
      flow: [
        { label: 'Factory by-products', desc: 'Pomegranate peel · fruit seeds · pomace · nut by-products' },
        { label: 'Primary processing', desc: 'Washing · (freeze) drying · milling · particle design' },
        { label: 'Korean R&D', desc: 'Analysis · extraction · standardization · certificates' },
        { label: 'New materials', desc: 'Food · beauty · industrial B2B supply' },
      ],
      cta: 'Visit MATERIAL LAB',
    },
    material: {
      eyebrow: '07 · MATERIAL VALUE', title: 'Food · Beauty · Ingredient',
      body: 'Apple pomace can become fiber, pomegranate peel a cosmetic extract, and nut by-products food ingredients.',
      cards: [
        { title: 'FOOD', from: 'Fruit & grain powders', to: 'RTE/RTD shakes · dietary fiber', desc: 'Uzbek fruit pulp powders commercialized with Korean recipes', placeholder: 'MAT-FOOD' },
        { title: 'BEAUTY', from: 'Pomegranate peel · fruit seeds', to: 'Extracts · natural scrub powders', desc: 'Polyphenol-standardized extracts and particle-graded scrub materials', placeholder: 'MAT-BEAUTY' },
        { title: 'INGREDIENT', from: 'Pomace · nut shells', to: 'Fiber · industrial materials', desc: 'Standardized powders with full documentation for B2B', placeholder: 'MAT-INGREDIENT' },
      ],
      cta: 'Ingredient collaboration',
    },
    market: {
      eyebrow: '08 · MARKET', title: 'Asia Distribution & B2B Network',
      body: 'From its Korean hub, SOLKERN distributes ERMÁK finished goods across 12 Asia-Pacific markets while building a Korean secondary-processing materials business.',
      nodes: [
        { name: 'UZBEKISTAN', role: 'Raw materials · ERMÁK production' },
        { name: 'TÜRKİYE', role: 'Fruit ingredients · by-products' },
        { name: 'KOREA', role: 'SOLKERN R&D · processing · distribution' },
        { name: 'ASIA-PACIFIC 12', role: '12 territory markets · finished goods & ingredients B2B' },
      ],
      cta: 'Partnership inquiry',
    },
    trust: {
      eyebrow: '09 · TRUST', title: 'Data-backed Origin Story',
      body: 'We only propose ingredients and products backed by analytical data, certifications, import standards and quality documents.',
      items: [
        { title: 'Certificates of Analysis', desc: 'Proposals based on safety test reports — pesticide residues, heavy metals, microbiology' },
        { title: 'Import standard review', desc: 'Item-by-item pre-review against the Korean Food Code and import safety rules' },
        { title: 'Label verification', desc: 'Only verified claims are used; unverified expressions are never shown' },
        { title: 'Certified production', desc: 'ISO 9001 · ISO 14001 · ISO 22000 (HACCP) · HALAL certified producers' },
      ],
      certs: ['ISO 9001:2015', 'ISO 14001:2015', 'ISO 22000:2018 (HACCP)', 'HALAL UAE.S GSO 2055-1'],
      cta: 'Request quality documents',
      note: '* Certifications are held by the ERMÁK production entities (ERMAKPLUS LLC · ZAFARHON LLC); item-level scope is confirmed on request.',
    },
    contact: { eyebrow: '10 · CONTACT', title: 'Partner with SOLKERN', body: 'Propose finished-goods distribution, ingredient supply, OEM/ODM or collaboration in Korea and Asia.', cta1: 'Contact us', cta2: 'Request catalog' },
    daily: {
      eyebrow: 'SOLKERN DAILY',
      title: 'ERMÁK in Everyday Life',
      body: 'From the breakfast table to an afternoon glass — moments where the fruit of Uzbekistan settles into a day in Korea.',
      captions: ['Morning · peanut butter toast', 'Afternoon · a glass of pomegranate juice', 'Tea time · QOQI fruit snack', 'Brunch · yogurt with cherry jam', 'Weekend · trekking with a nut bar', 'Café · ayran and qurt'],
    },
    timeline: {
      eyebrow: 'SINCE 1992',
      title: 'From the land of origin to Korean technology — a continuing story',
      items: [
        { year: '1992', title: 'ERMÁK founded', desc: 'The natural-food brand ERMÁK begins in Tashkent, Uzbekistan.' },
        { year: '2008', title: 'Factory-processed sunflower seeds · factory-made qurt', desc: 'The first in Uzbekistan to process and pack sunflower seeds in a factory and to produce traditional qurt at scale.' },
        { year: '2025', title: 'Asia-Pacific 12-market rights for ERMÁK', desc: 'CATKIN Co., Ltd. secures distribution rights for ERMÁK finished goods in 12 Asia-Pacific markets.' },
        { year: '2026.06', title: 'ERMÁK · ASIL Korean catalog published', desc: 'Korean-language catalog covering 8 ERMÁK categories and ASIL juices and sauces.' },
        { year: '2026.08', title: 'SOLKERN Co., Ltd. established', desc: 'Founded in Cheongna, Incheon as the official partner for ERMÁK’s joint entry into Asia, starting distribution and ingredient R&D.' },
        { year: '2026.09', title: 'First pomegranate-peel powder order', desc: 'A 100 kg order of freeze-dried pomegranate-peel powder opens the first MATERIAL LAB project.' },
      ],
    },
  },
  solkern: {
    hero: { eyebrow: 'ABOUT SOLKERN', title: 'We discover good ingredients, build markets, and bring what remains back to life.', body: 'SOLKERN Co., Ltd. connects the natural foods and fruit ingredients of Uzbekistan and Türkiye to Korea and Asia as an ingredient, distribution and R&D company.' },
    statement: 'Origin → Product → Second Life → Market. One continuous flow from Central Asian raw materials to ERMÁK finished goods and Korean secondary-processing materials.',
    identity: [
      { title: 'Official Asia Co-expansion Partner of ERMÁK', body: 'We introduce the finished goods of ERMÁK, Uzbekistan’s leading natural food brand since 1992, and its juice brand ASIL to Korea and 12 Asia-Pacific markets.' },
      { title: 'Ingredient R&D · Korean processing', body: 'We analyze, process and standardize fruit ingredients and production by-products (peel, seeds, pomace) into food, beauty and industrial materials.' },
      { title: 'Trust finished with data', body: 'Emotion begins in nature; B2B trust is completed with certificates of analysis, certifications and import-standard reviews.' },
    ],
    business: [
      { title: 'Finished-goods distribution', desc: 'ERMÁK · ASIL products in Korea and Asia', items: ['Official online brand store', 'Warehouse clubs & major retail', 'Food service, bakery & café B2B', 'Asian partner distribution'] },
      { title: 'Ingredient supply', desc: 'Fruit ingredients, powders and by-products from Uzbekistan & Türkiye', items: ['Pulp, peel and seed powders', 'Freeze-dried ingredients', 'Supplied with spec sheets & COA', 'MOQ & samples negotiable'] },
      { title: 'R&D · OEM/ODM', desc: 'Materials and products through Korean secondary processing', items: ['Analysis, extraction, standardization', 'Novel food ingredient track', 'Cosmetic ingredients & scrub powders', 'OEM/ODM product development'] },
    ],
    partners: [
      { name: 'ZAFARXON · ERMÁK', role: 'Production in Uzbekistan', desc: 'ERMAKPLUS LLC · ZAFARHON LLC. Production bases in Tashkent and Jizzakh, ISO · HACCP · HALAL certified lines.' },
      { name: 'CATKIN Co., Ltd.', role: 'Import & customs partner', desc: 'Holder of ERMÁK distribution rights for 12 Asia-Pacific markets (Korea, China, Japan, Taiwan, Hong Kong, Mongolia, Vietnam, Thailand, Malaysia, Indonesia, Philippines, Australia). Handles import, customs, quarantine and domestic warehousing.' },
      { name: 'SOLKERN Co., Ltd.', role: 'Sales · R&D · OEM/ODM', desc: 'Product planning, marketing, channel operation, ingredient R&D and OEM/ODM production of CATKIN-developed products.' },
    ],
    info: [
      { label: 'Company', value: 'SOLKERN Co., Ltd.' },
      { label: 'CEO', value: 'Jin-Tae Park' },
      { label: 'Founded', value: 'August 2026' },
      { label: 'Business', value: 'Food wholesale & retail · Ingredient R&D · IT (app development)' },
      { label: 'Address', value: '5F 505-J341, 10-20 Jungbong-daero 612beon-gil, Seo-gu, Incheon, Korea (Cheongna Plaza)' },
      { label: 'Email', value: 'solkern@solkern.kr' },
    ],
    founderQuote: { quote: 'The product we make and pack today, a child will eat tomorrow. Perhaps my son or my grandchild. That is why every one of us thinks of ourselves and our children when we create a product.', who: 'Valijon Salixov · Founder of ERMÁK' },
  },
  origin: {
    hero: { eyebrow: 'ORIGIN', title: 'The Land Makes the Ingredient', body: 'Sunlight, soil, climate and a long orchard culture. Good products start with good ingredients.' },
    chapters: [
      { num: '01', title: 'Sun', body: 'Uzbekistan lies in a continental climate with many clear days a year. Long, strong sunlight is the most important condition for the color and aroma of fruit.', placeholder: 'ORIGIN-SUN', note: 'Morning light over a Fergana Valley orchard, backlit pomegranate trees' },
      { num: '02', title: 'Soil & water', body: 'Meltwater from the Tian Shan and a tradition of oasis agriculture — the reason fruit grows in the heart of a dry continent.', placeholder: 'ORIGIN-SOIL', note: 'Irrigation canals and red earth, soil and apricots in a hand' },
      { num: '03', title: 'Orchard culture', body: 'Fruit growing and drying skills passed down since the Silk Road. Apricot, pomegranate, grape and melon are daily life and culture here.', placeholder: 'ORIGIN-CULTURE', note: 'Apricots drying on rooftops, piles of nuts at a bazaar' },
      { num: '04', title: 'Making', body: 'ERMÁK has made natural foods in Uzbekistan since 1992 — pressing, drying and roasting by the season of each ingredient.', placeholder: 'ORIGIN-FACTORY', note: 'Clean production line, stainless press and glass bottle filling' },
    ],
    regions: [
      { name: 'Fergana Valley', desc: 'Uzbekistan’s largest orchard region. Apricot, cherry, pomegranate and grape.', crops: ['Apricot', 'Cherry', 'Pomegranate', 'Grape'] },
      { name: 'Tashkent · Jizzakh', desc: 'ERMÁK production bases. Sunflower seed & nut processing and fermented dairy snacks.', crops: ['Sunflower seeds', 'Nuts', 'Qurt'] },
      { name: 'Samarkand · Bukhara', desc: 'Historic centers of dried fruit and nut trade.', crops: ['Dried apricot', 'Raisins', 'Almond'] },
      { name: 'Türkiye', desc: 'Second origin for fruit ingredients and by-products — hazelnut, fig, apricot, pomegranate.', crops: ['Hazelnut', 'Fig', 'Pomegranate', 'Apricot'] },
    ],
    turkiye: { title: 'Our second origin, Türkiye', body: 'Fruit ingredients from the Mediterranean and the Anatolian plateau form the second pillar of SOLKERN’s ingredient business. Reviewing Uzbek and Turkish sources together secures stability across seasons, varieties and volumes.', placeholder: 'ORIGIN-TURKIYE' },
    disclaimer: '* Origin descriptions are based on general regional information. Claims requiring testing — superiority or compositional comparisons — will be added only as a data-backed story once analytical data is secured.',
  },
  ermak: {
    hero: { eyebrow: 'ERMÁK · SINCE 1992', title: 'ERMÁK, The Taste You Trust', body: 'SOLKERN introduces ERMÁK products, made since 1992, to Asian markets. “Ermák” means joy and leisurely time in Uzbek.' },
    brandStory: {
      title: 'A pioneer of healthy snacks in Uzbekistan',
      body: 'In 2008, the first brand in Uzbekistan to process and pack sunflower seeds industrially and to produce the traditional fermented dairy snack qurt at scale. Eight product categories from Tashkent and Jizzakh, alongside the juice brand ASIL.',
      facts: [
        { value: '1992', label: 'Founded' },
        { value: '850+', label: 'Employees' },
        { value: '8', label: 'Product categories' },
        { value: '4', label: 'International certifications (ISO 9001·14001·22000·HALAL)' },
      ],
    },
    newProducts: { badge: 'NEW 2026/27', title: 'QOQI · Challpak — The Third State of Fruit', body: 'Neither fresh (1st) nor traditionally dried (2nd): a third state. QOQI gently dries ripe apricot, persimmon and Ajwa date purees; Challpak is apricot and cherry fruit leather. Both are new in the 2026/27 catalog.', cta: 'See fruit snacks' },
    categoriesTitle: 'ERMÁK · ASIL product categories',
    categories: ko.ermak.categories.map((c) => ({
      ...c,
      name: c.en,
      desc: {
        juice: 'Apple, quince, pomegranate, apple-beet, cherry, apricot. Direct-pressed juices and fruit nectars.',
        paste: 'Peanut, cashew and sesame (tahini) pastes and date confiture.',
        jam: 'Pomegranate, grape, cherry, apricot, date and quince jams; pomegranate and cherry sauces.',
        seeds: 'Black and white sunflower seeds (salted / unsalted / roasted), from small packs to 2 kg bulk.',
        nuts: 'Almond, cashew, pistachio, peanut, sunflower kernels, pumpkin seeds, nut mix and nut & dried fruit mix.',
        qurt: 'Traditional Central Asian dried fermented dairy: qurt, bioqurt, and qurtoba & ayran drinks.',
        bar: 'Pumpkin seed, almond, sesame, mixed nut, peanut and sunflower seed bars.',
        snack: 'New for 2026/27: QOQI — apricot, persimmon and Ajwa date purees gently dried — and Challpak apricot and cherry fruit leather. “The Third State of Fruit”.',
        other: 'Dry bread rings (teshik kulcha / sushki, 3 kinds) and apple, apricot and quince purees.',
      }[c.id] as string,
      point: {
        juice: 'Hero category most directly tied to the origin story',
        paste: 'Natural spread positioning · brunch & bakery B2B',
        jam: 'Yogurt, brunch, bakery and food-service B2B',
        seeds: 'Small-pack and bulk in parallel · warehouse-club candidate',
        nuts: 'Convenient healthy snack · online test SKU candidate',
        qurt: 'Strong Central Asian identity · consumer-education launch',
        bar: 'Convenient healthy snack · online test SKU candidate',
        snack: 'The newest format for Korean consumers · #1 online test SKU',
        other: 'Locally distinctive line · secondary or test line',
      }[c.id] as string,
      products: c.products.map((p) => ({
        ...p,
        name: ({
          j1: 'Pomegranate juice', j2: 'Apple juice', j3: 'Quince juice', j4: 'Cherry juice', j5: 'Apricot nectar', j6: 'Apple-beet juice',
          p1: 'Peanut butter', p2: 'Cashew butter', p3: 'Sesame paste (tahini)', p4: 'Date confiture',
          m1: 'Pomegranate jam', m2: 'Grape jam', m3: 'Cherry · apricot · quince jam', m4: 'Cherry sauce · pomegranate sauce',
          s1: 'Black sunflower seeds', s2: 'White sunflower seeds', s3: 'Roasted sunflower seeds, bulk',
          n1: 'Almonds', n2: 'Cashews', n3: 'Sunflower kernels', n4: 'Nut mix',
          q1: 'Bioqurt', q2: 'Qurt (balls)', q3: 'Hot pepper qurt', q4: 'Qurtoba', q5: 'Basil ayran',
          b1: 'Pumpkin seed bar', b2: 'Almond bar', b3: 'Sesame · sunflower bar',
          o1: 'Salted dry bread rings', o2: 'Stevia & white sesame rings', o3: 'White sesame & black cumin rings', o12: 'Fruit puree',
          o4: 'Apricot QOQI', o5: 'Persimmon QOQI', o6: 'Ajwa date QOQI', o7: 'Apricot Challpak (Bargak)', o8: 'Apricot Challpak (Kantek)', o9: 'Cherry Challpak', o10: 'QOQI large pack (apricot)', o11: 'Challpak large pack (cherry)',
          n5: 'Salted nut mix', n6: 'Nut & dried fruit mix', n7: 'Salted pumpkin seeds (in shell)', q6: 'Basil qurt', q8: 'Hard qurt (Toshqurt)', q7: 'Square-shaped basil qurt',
        } as Record<string, string>)[p.id] || p.name,
        sub: p.sub?.replace('냉압착', 'cold-pressed'),
        sizes: p.sizes?.replace(/대용량/g, 'large'),
      })),
    })),
    korea: {
      title: 'Korea Launch Roadmap', body: 'The Korean launch proceeds in phases, starting with channel-fit items.',
      phases: [
        { phase: 'PHASE 1', items: 'Seeds & nuts · jams & pastes · dried fruit', channel: 'Official online store · small-pack channels' },
        { phase: 'PHASE 2', items: 'ASIL juices (6) · sauces', channel: 'Warehouse clubs · food service & café B2B' },
        { phase: 'PHASE 3', items: 'Qurt · fermented dairy drinks', channel: 'After confirming livestock-product import requirements' },
      ],
    },
    cta: { title: 'Need the full product catalog?', body: 'We will send the ERMÁK 2026/27 and ASIL catalogs with item-level spec sheets.', button: 'Request catalog' },
  },
  materialLab: {
    hero: { eyebrow: 'MATERIAL LAB · PROJECT 2', title: 'Nothing Ends at the Factory', body: 'Peels, seeds and pomace left after processing are turned into new food and material value.' },
    thesis: { title: 'The greatest value is not in powder, but in “standardized ingredients”', body: 'Supplying what used to be discarded — clean, uniform and fully documented. SOLKERN MATERIAL LAB creates value through quality assurance and consistency, not novelty.' },
    tracks: [
      { id: 'beauty', title: 'Beauty materials', en: 'BEAUTY', body: 'Polyphenol-standardized pomegranate peel extracts and natural scrub powders from fruit seeds and peels, graded by particle size for different skin types.', materials: ['Pomegranate peel extract', 'Pomegranate · cherry · apricot seed powder', 'Walnut shell · grape seed powder'], stage: 'Sourcing · first order in progress', placeholder: 'LAB-BEAUTY' },
      { id: 'food', title: 'Food materials', en: 'FOOD', body: 'RTE/RTD shakes based on fruit and grain powders, and apple pomace fiber. A novel-ingredient approval track runs in parallel so usable ingredients come first.', materials: ['Fruit pulp powders (pomegranate, cherry, apricot, apple…)', 'Grain powders', 'Pomace dietary fiber'], stage: 'Recipe development · feasibility', placeholder: 'LAB-FOOD' },
      { id: 'ingredient', title: 'Industrial materials', en: 'INGREDIENT', body: 'Mesh-graded abrasives and fillers from walnut shells and other nut by-products, supplied as B2B ingredients with spec sheets and test reports.', materials: ['Walnut shell abrasive', 'Nut by-product fillers', 'Standardized powders'], stage: 'Sourcing review', placeholder: 'LAB-INDUSTRY' },
    ],
    process: [
      { step: '01', title: 'Sourcing', desc: 'By-products from Uzbekistan & Türkiye; freeze-drying and milling' },
      { step: '02', title: 'Analysis', desc: 'Composition, pesticide residues, heavy metals; certificates of analysis' },
      { step: '03', title: 'Regulatory review', desc: 'Usable scope under the Food Code and cosmetic ingredient rules' },
      { step: '04', title: 'Secondary processing', desc: 'Extraction, fractionation, particle design, standardization in Korea' },
      { step: '05', title: 'Commercialization · B2B', desc: 'Ingredient supply, OEM/ODM development, partner collaboration' },
    ],
    principles: [
      { title: 'Regulation first', desc: 'We confirm usability and approval tracks before investing.' },
      { title: 'Speak with data', desc: 'No unverified efficacy or comparison claims — we propose with COAs and spec sheets.' },
      { title: 'Residue is a resource', desc: 'Pectin and fiber left after extraction are designed as secondary revenue.' },
    ],
    cta: { title: 'Propose an ingredient collaboration', body: 'By-product supply, joint R&D, ingredient purchase, OEM/ODM — every form of collaboration is welcome.', button: 'Ingredient inquiry' },
  },
  b2b: {
    hero: { eyebrow: 'B2B', title: 'Partner with SOLKERN', body: 'Finished-goods distribution, ingredient supply, OEM/ODM, Korean secondary processing and Asian market collaboration.' },
    services: [
      { id: 'dist', title: 'Finished-goods distribution', desc: 'Partnerships for ERMÁK · ASIL products in Korea and Asia', bullets: ['Warehouse clubs & major retail', 'Online channel supply', 'Food service, café & bakery B2B', 'Country partners across Asia'] },
      { id: 'raw', title: 'Ingredient supply', desc: 'Standardized fruit ingredients, powders and by-products', bullets: ['Pulp, peel & seed powders', 'Freeze-dried ingredients', 'COA & spec sheets included', 'MOQ & lead time negotiable'] },
      { id: 'oem', title: 'OEM / ODM', desc: 'Product development through Korean secondary processing', bullets: ['Food products such as shakes & spreads', 'Beauty ingredients such as scrubs & extracts', 'Packaging & labeling review support', 'Small pilot runs negotiable'] },
      { id: 'sample', title: 'Samples & documents', desc: 'Product samples and quality documentation', bullets: ['Product catalogs (ERMÁK · ASIL)', 'Item spec sheets', 'Certificates of analysis & certifications', 'Sample shipping arrangements'] },
    ],
    steps: [
      { step: '01', title: 'Inquiry', desc: 'Tell us your items of interest, use and quantity via the form or email.' },
      { step: '02', title: 'Documents · samples', desc: 'We provide catalogs, spec sheets, COAs and samples.' },
      { step: '03', title: 'Terms', desc: 'Price, MOQ, lead time, Incoterms and payment terms.' },
      { step: '04', title: 'Contract · supply', desc: 'After contracting, goods are imported, cleared and delivered domestically.' },
    ],
    docs: ['Product catalog', 'Item spec sheets', 'Certificates of analysis (COA)', 'ISO · HALAL certificates', 'Certificate of origin', 'Label information'],
    faq: [
      { q: 'What is the minimum order quantity (MOQ)?', a: 'It depends on the item and pack size. Share your target quantity and we will advise item-level MOQ and lead time.' },
      { q: 'Can I receive samples?', a: 'Yes. After a B2B inquiry we agree on sample items and quantities; shipping costs are agreed in advance.' },
      { q: 'Can I buy ingredients (by-products) in small quantities?', a: 'We support small R&D sample purchases, supplied with specifications and test reports.' },
      { q: 'Do you supply outside Korea?', a: 'Yes. We work with partners in the 12 Asia-Pacific territory markets under the ERMÁK distribution agreement (Korea, China, Japan, Taiwan, Hong Kong, Mongolia, Vietnam, Thailand, Malaysia, Indonesia, Philippines, Australia). The five Central Asian countries are managed directly by ERMÁK headquarters.' },
    ],
    cta: { title: 'Start your B2B conversation', button: 'B2B inquiry' },
  },
  news: {
    hero: { eyebrow: 'NEWS', title: 'SOLKERN Journal', body: 'Trips, contracts, launches, exhibitions and R&D progress.' },
    empty: 'No posts yet.',
    items: [
      { id: 'n-2026-09-01', date: '2026.09', category: 'R&D', title: 'First 100 kg freeze-dried pomegranate peel powder ordered', summary: 'As the first step of the pomegranate peel extract business, we ordered 100 kg of freeze-dried powder. Analysis and standardization begin.', placeholder: 'NEWS-POMEGRANATE' },
      { id: 'n-2026-08-01', date: '2026.08', category: 'COMPANY', title: 'SOLKERN Co., Ltd. incorporated', summary: 'SOLKERN was incorporated in Cheongna, Incheon, launching ERMÁK distribution and ingredient R&D in earnest.', placeholder: 'NEWS-OFFICE' },
      { id: 'n-2026-06-01', date: '2026.06', category: 'PRODUCT', title: 'ERMÁK · ASIL Korean catalogs published', summary: 'Korean catalogs covering eight ERMÁK categories and six ASIL juices plus two sauces were published.', placeholder: 'NEWS-CATALOG' },
    ],
  },
  contact: {
    hero: { eyebrow: 'CONTACT', title: 'Partner with SOLKERN', body: 'Propose finished-goods distribution, ingredient supply, OEM/ODM or collaboration in Korea and Asia. We reply within two business days.' },
    form: {
      name: 'Your name', company: 'Company', email: 'Email', phone: 'Phone', country: 'Country / region',
      type: 'Inquiry type', typeOptions: ['Finished-goods distribution', 'Ingredient supply', 'OEM / ODM', 'Samples · catalog request', 'Ingredient collaboration · R&D', 'Other'],
      product: 'Items / ingredients of interest', quantity: 'Expected quantity · MOQ', message: 'Message',
      agree: 'I agree to the collection and use of personal data (for replying to this inquiry, retained for 1 year)', submit: 'Send inquiry',
      success: 'Your inquiry has been received', successBody: 'Our team will review it and reply by email or phone.',
      privacy: 'Collected: name, company, email, phone, message · Purpose: replying to your inquiry · Retention: 1 year',
    },
    info: ko.contact.info,
    officeTitle: 'OFFICE',
    address: '5F 505-J341, 10-20 Jungbong-daero 612beon-gil, Seo-gu, Incheon, Korea (Cheongna Plaza)',
  },
  territory: {
    eyebrow: 'DISTRIBUTION TERRITORY',
    title: 'Asia-Pacific 12 Markets',
    body: 'Under the ERMÁK distribution agreement, we supply ERMÁK finished goods to 12 markets across Northeast Asia, Southeast Asia and Oceania, with Korea as our hub.',
    countLabel: 'Territory markets',
    regions: [
      { name: 'Northeast Asia', countries: [
        { code: 'KR', name: 'Korea', city: 'Incheon · hub' },
        { code: 'CN', name: 'China', city: 'Beijing' },
        { code: 'JP', name: 'Japan', city: 'Tokyo' },
        { code: 'TW', name: 'Taiwan', city: 'Taipei' },
        { code: 'HK', name: 'Hong Kong', city: 'Hong Kong' },
        { code: 'MN', name: 'Mongolia', city: 'Ulaanbaatar' },
      ] },
      { name: 'Southeast Asia', countries: [
        { code: 'VN', name: 'Vietnam', city: 'Hanoi' },
        { code: 'TH', name: 'Thailand', city: 'Bangkok' },
        { code: 'MY', name: 'Malaysia', city: 'Kuala Lumpur' },
        { code: 'ID', name: 'Indonesia', city: 'Jakarta' },
        { code: 'PH', name: 'Philippines', city: 'Manila' },
      ] },
      { name: 'Oceania', countries: [{ code: 'AU', name: 'Australia', city: 'Sydney' }] },
    ],
    origins: [
      { code: 'UZ', name: 'Uzbekistan', role: 'ERMÁK production · origin' },
      { code: 'TR', name: 'Türkiye', role: 'Fruit ingredients · by-products' },
    ],
    hub: 'Hub',
    legendTerritory: '12 territory markets',
    legendOrigin: 'Origin',
    legendDirect: 'Central Asia (managed directly by ERMÁK)',
    note: '* Territory as defined in the ERMÁK distribution agreement. The five Central Asian countries (Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan, Uzbekistan) are managed directly by ERMÁK headquarters. Country-specific supply terms are available on B2B inquiry.',
    tapHint: 'Tap a country to highlight it on the map',
  },
  ui: {
    langName: 'English',
    sections: { solkernBusiness: 'Three businesses, one flow', solkernPartners: 'From production to sales: a three-company structure', companyInfo: 'Company information', originRegions: 'Where the ingredients grow', labTracks: 'Three material tracks', labProcess: 'From by-product to standardized ingredient', b2bServices: 'How we work together', b2bProcess: 'From inquiry to supply', b2bFaq: 'Frequently asked questions' },
    originMarquee: ['Sun', 'Soil', 'Climate', 'Orchard culture', 'Uzbekistan', 'Türkiye', 'Pomegranate', 'Apricot', 'Cherry', 'Nuts'],
    table: { region: 'Region', country: 'Country', city: 'Key city' },
    regionsLabel: 'Regions', originsLabel: 'Origins',
    prev: 'Previous', next: 'Next',
    productNote: '* Specifications and label claims are finalized per import label; item spec sheets are provided on catalog request.',
    countryPlaceholder: 'Korea',
    privacy: {
      title: 'Privacy Policy',
      intro: 'SOLKERN Co., Ltd. (the "Company") collects and uses personal data for handling website inquiries as follows.',
      items: ['Items: name, company, email, phone, country, message', 'Purpose: replying to inquiries; providing quotes, samples and documents', 'Retention: 1 year from receipt, or as required by applicable law', 'Third-party disclosure: none, except as required by law'],
      officer: 'Data Protection Officer: Jin-Tae Park',
    },
  },
  footer: {
    tagline: 'From Origin to New Value',
    company: 'SOLKERN Co., Ltd.',
    ceo: 'Data Protection Officer: Jin-Tae Park',
    regNo: 'Business registration no. 443-86-03703',
    address: '5F 505-J341, 10-20 Jungbong-daero 612beon-gil, Seo-gu, Incheon, Korea',
    email: 'solkern@solkern.kr',
    tel: '+82-10-4589-1030',
    copyright: '© 2026 SOLKERN Co., Ltd. All rights reserved.',
    links: [
      { label: 'Privacy policy', href: '/privacy' },
      { label: 'Admin', href: '/admin' },
    ],
  },
};
