import type { Dict } from './types';

export const ko: Dict = {
  meta: {
    title: 'SOLKERN | From Origin to New Value — 우즈베키스탄·튀르키예 자연 식품과 원료 R&D',
    description:
      '㈜솔컨은 우즈베키스탄·튀르키예의 자연친화 식품 브랜드 ERMÁK·ASIL의 완제품을 아시아 시장에 소개하고, 과일 원료·부산물을 한국의 기술로 새로운 소재로 전환하는 원료 R&D 기업입니다.',
  },
  nav: [
    { label: 'SOLKERN', href: '/solkern' },
    { label: 'ORIGIN', href: '/origin' },
    { label: 'ERMÁK', href: '/ermak' },
    { label: 'MATERIAL LAB', href: '/material-lab' },
    { label: 'B2B', href: '/b2b' },
    { label: 'NEWS', href: '/news' },
    { label: 'CONTACT', href: '/contact' },
  ],
  common: {
    more: '더 보기',
    contact: '문의하기',
    catalog: '카탈로그 요청',
    b2b: 'B2B 상담',
    viewProducts: 'ERMÁK 제품 보기',
    viewMaterial: '원료·B2B 사업 보기',
    scroll: 'SCROLL',
    langLabel: '언어',
    readMore: '자세히 보기',
    back: '목록으로',
    send: '보내기',
    sending: '전송 중…',
    sent: '전송 완료',
    error: '전송에 실패했습니다. 잠시 후 다시 시도해 주세요.',
    required: '필수',
    officialDistributor: 'ERMÁK 아시아 공동진출 공식파트너',
  },
  home: {
    hero: {
      eyebrow: 'Quality Without Borders · ERMÁK 아시아 공동진출 공식파트너 · 원료 R&D',
      title: 'From Origin',
      titleAccent: 'to New Value',
      body: '우즈베키스탄의 자연에서 자란 원물이 아시아의 식탁을 만나고, 한국의 기술을 통해 또 다른 가치로 이어집니다.',
      cta1: 'ERMÁK 제품 보기',
      cta2: '원료·B2B 사업 보기',
    },
    journey: {
      eyebrow: 'THE SOLKERN WAY',
      title: '좋은 원물을 발견하고, 시장을 만들고, 남은 가치까지 다시 살립니다.',
      steps: [
        { key: 'origin', label: '01 ORIGIN', title: '원물이 자라는 땅', body: '강한 햇빛, 대륙성 기후, 오랜 과수 재배 문화. 우즈베키스탄과 튀르키예의 과일·견과는 이야기에서 시작됩니다.' },
        { key: 'product', label: '02 PRODUCT', title: 'ERMÁK 완제품', body: '1992년부터 이어진 ERMÁK의 주스·잼·너트버터·씨앗·쿠르트·넛바를 SOLKERN이 아시아 시장에 소개합니다.' },
        { key: 'second', label: '03 SECOND LIFE', title: '공장에서 끝나지 않는 가치', body: '제조 후 남는 껍질·씨앗·박을 한국의 가공 기술로 식품·뷰티·산업 소재로 전환합니다.' },
        { key: 'market', label: '04 MARKET', title: '아시아 유통 · B2B 네트워크', body: '완제품 유통, 원료 공급, OEM/ODM. 한국을 거점으로 아시아 파트너와 함께 시장을 만듭니다.' },
      ],
    },
    land: {
      eyebrow: '02 · THE LAND',
      title: 'Why Central Asia, Why Uzbekistan',
      body: '강한 햇빛, 대륙성 기후, 오랜 과수 재배 문화가 다양한 과일과 견과를 키워냅니다. 좋은 제품은 좋은 원물에서 시작됩니다.',
      facts: [
        { value: '300+', label: '연간 일조일(지역 평균 추정)' },
        { value: '1992', label: 'ERMÁK 창립 연도' },
        { value: '2', label: '핵심 원산지 — 우즈베키스탄 · 튀르키예' },
        { value: '9', label: 'ERMÁK 제품 카테고리' },
      ],
      cta: '원산지 스토리 더 보기',
    },
    fruit: {
      eyebrow: '03 · THE FRUIT',
      title: 'One Origin, Many Possibilities',
      body: '석류, 살구, 체리, 사과, 포도, 견과. 하나의 원물은 완제품과 소재로 동시에 확장됩니다.',
      items: [
        { name: '석류', product: '주스 · 잼 · 소스', material: '껍질 추출물 · 씨앗 파우더', image: '/images/fruits/pomegranate.webp' },
        { name: '사과', product: '주스 · 퓨레', material: '사과박 파이버', image: '/images/fruits/apple.webp' },
        { name: '체리', product: '주스 · 잼 · 소스', material: '씨앗 스크럽 파우더', image: '/images/fruits/cherry.webp' },
        { name: '살구', product: '코키 · Challpak · 넥타 · 잼', material: '씨앗·과피 소재', placeholder: 'FRUIT-APRICOT' },
        { name: '견과·씨앗', product: '너트버터 · 넛바 · 로스팅', material: '견과 부산물 식품소재', placeholder: 'FRUIT-NUTS' },
        { name: '포도·대추야자', product: '잼 · 콘피튀르', material: '포도씨 · 과피 소재', placeholder: 'FRUIT-GRAPE' },
      ],
      cta: '원물별 가능성 보기',
    },
    collection: {
      eyebrow: '04 · ERMÁK COLLECTION',
      title: 'The Taste You Trust',
      body: '주스·넥타, 너트버터, 잼·소스, 씨앗·견과, 쿠르트, 넛바까지 — ERMÁK의 대표 제품군을 소개합니다.',
      cta: '제품 카탈로그 요청',
    },
    featured: {
      eyebrow: '05 · FEATURED PRODUCTS',
      title: 'Korea Launch Priority',
      body: '한국 런칭은 씨앗·견과, 잼·페이스트, 주스, 쿠르트 등 채널별 적합 품목부터 단계적으로 진행합니다.',
      cta: 'B2B 상담',
      tags: ['온라인 테스트 SKU', '창고형 매장 대용량', '외식·베이커리 B2B', '소포장 편의 채널'],
    },
    secondLife: {
      eyebrow: '06 · SECOND LIFE',
      title: 'Nothing Ends at the Factory',
      body: '제조가 끝났다고 원료의 가치가 끝나는 것은 아닙니다. 껍질, 씨앗, 박은 한국의 가공 기술로 새로운 소재가 됩니다.',
      flow: [
        { label: '공장 부산물', desc: '석류 껍질 · 과일 씨앗 · 착즙박 · 견과 부산물' },
        { label: '1차 가공', desc: '세척 · 건조(동결건조) · 분쇄 · 입도 설계' },
        { label: '한국 R&D', desc: '성분 분석 · 추출 · 규격화 · 시험성적서' },
        { label: '새로운 소재', desc: '식품 · 뷰티 · 산업 소재 B2B 공급' },
      ],
      cta: 'MATERIAL LAB 보기',
    },
    material: {
      eyebrow: '07 · MATERIAL VALUE',
      title: 'Food · Beauty · Ingredient',
      body: '사과박은 파이버로, 석류껍질은 코스메틱 추출물로, 견과 부산물은 식품 소재로 확장될 수 있습니다.',
      cards: [
        { title: 'FOOD', from: '과육·곡물 분말', to: 'RTE/RTD 쉐이크 · 식이섬유', desc: '우즈벡 과일 과육 분말을 한국 레시피로 상품화', placeholder: 'MAT-FOOD' },
        { title: 'BEAUTY', from: '석류껍질 · 과일 씨앗', to: '추출물 · 천연 스크럽 파우더', desc: '폴리페놀 표준화 추출물과 입도별 스크럽 원료', placeholder: 'MAT-BEAUTY' },
        { title: 'INGREDIENT', from: '착즙박 · 견과 껍질', to: '파이버 · 산업용 소재', desc: '규격화된 분말과 서류를 갖춘 B2B 원료', placeholder: 'MAT-INGREDIENT' },
      ],
      cta: '원료 협업 문의',
    },
    market: {
      eyebrow: '08 · MARKET',
      title: 'Asia Distribution & B2B Network',
      body: 'SOLKERN은 한국을 거점으로 아시아·태평양 12개국에 ERMÁK 완제품을 유통하고, 한국 2차 가공 소재 사업을 함께 추진합니다.',
      nodes: [
        { name: 'UZBEKISTAN', role: '원물 · ERMÁK 생산' },
        { name: 'TÜRKİYE', role: '과일 원료 · 부산물' },
        { name: 'KOREA', role: 'SOLKERN R&D · 2차 가공 · 유통' },
        { name: 'ASIA-PACIFIC 12', role: '판권 12개국 완제품 · 원료 B2B' },
      ],
      cta: '파트너십 문의',
    },
    trust: {
      eyebrow: '09 · TRUST',
      title: 'Data-backed Origin Story',
      body: '분석 데이터, 인증, 수입 기준, 품질 서류를 갖춘 원료와 제품만 시장에 제안합니다.',
      items: [
        { title: '시험성적서(COA)', desc: '잔류농약·중금속·미생물 등 안전성 항목 성적서 기반 제안' },
        { title: '수입 기준 검토', desc: '식품공전·수입식품안전관리 기준에 따른 품목별 사전 검토' },
        { title: '라벨·표시 검증', desc: '표시 가능한 문구만 사용, 검증 전 표현은 쓰지 않습니다' },
        { title: '생산 인증', desc: 'ISO 9001 · ISO 14001 · ISO 22000(HACCP) · HALAL 인증 생산 법인' },
      ],
      certs: ['ISO 9001:2015', 'ISO 14001:2015', 'ISO 22000:2018 (HACCP)', 'HALAL UAE.S GSO 2055-1'],
      cta: '품질 자료 요청',
      note: '※ 인증은 ERMÁK 생산 법인(ERMAKPLUS LLC · ZAFARHON LLC) 보유 인증 기준이며, 품목별 적용 범위는 자료 요청 시 확인해 드립니다.',
    },
    contact: {
      eyebrow: '10 · CONTACT',
      title: 'Partner with SOLKERN',
      body: '완제품 유통, 원료 공급, OEM/ODM, 한국 및 아시아 시장 협업을 제안해 주세요.',
      cta1: '문의하기',
      cta2: '카탈로그 요청',
    },
  },
  solkern: {
    hero: { eyebrow: 'ABOUT SOLKERN', title: '좋은 원물을 발견하고, 시장을 만들고, 남은 가치까지 다시 살립니다.', body: '㈜솔컨은 우즈베키스탄·튀르키예의 자연친화 식품과 과일 원료를 한국과 아시아 시장에 연결하는 원료·유통·R&D 기업입니다.' },
    statement: 'Origin → Product → Second Life → Market. 중앙아시아 원물에서 ERMÁK 완제품, 그리고 한국 2차 가공 소재 사업까지 하나의 흐름으로 연결합니다.',
    identity: [
      { title: 'ERMÁK 아시아 공동진출 공식파트너', body: '1992년부터 이어진 우즈베키스탄 대표 자연 식품 브랜드 ERMÁK과 주스 브랜드 ASIL의 완제품을 한국을 비롯한 아시아·태평양 12개국 시장에 소개합니다.' },
      { title: '원료 R&D · 한국 2차 가공', body: '과일 원료와 제조 부산물(껍질·씨앗·박)을 분석·가공·규격화하여 식품·뷰티·산업 소재로 전환합니다.' },
      { title: '데이터로 마무리하는 신뢰', body: '감성은 자연에서 시작하되, B2B 신뢰는 시험성적서·인증·수입 기준 검토로 마무리합니다.' },
    ],
    business: [
      { title: '완제품 유통', desc: 'ERMÁK · ASIL 완제품의 한국·아시아 유통', items: ['온라인 공식 브랜드숍', '창고형 매장·대형 유통 납품', '외식·베이커리·카페 B2B', '아시아 파트너 유통'] },
      { title: '원료 공급', desc: '우즈베키스탄·튀르키예 과일 원료·분말·부산물 공급', items: ['과육·과피·씨앗 분말', '동결건조 원료', '규격서·COA 동반 공급', 'MOQ·샘플 협의'] },
      { title: 'R&D · OEM/ODM', desc: '한국 2차 가공을 통한 소재화와 상품화', items: ['성분 분석·추출·규격화', '식품 원료 인정 트랙', '화장품 원료·스크럽 파우더', 'OEM/ODM 상품 개발'] },
    ],
    partners: [
      { name: 'ZAFARXON · ERMÁK', role: '우즈베키스탄 생산', desc: 'ERMAKPLUS LLC · ZAFARHON LLC. 타슈켄트·지자흐 생산 거점, ISO·HACCP·HALAL 인증 라인.' },
      { name: '㈜캣킨 CATKIN', role: '수입 · 통관 파트너', desc: 'ERMÁK 아시아·태평양 12개국 판권 보유(한국·중국·일본·대만·홍콩·몽골·베트남·태국·말레이시아·인도네시아·필리핀·호주). 수입·통관·검역과 국내 창고 입고를 담당합니다.' },
      { name: '㈜솔컨 SOLKERN', role: '판매 · R&D · OEM/ODM', desc: '상품 기획·마케팅·채널 운영과 원료 R&D, 캣킨 개발 상품의 OEM/ODM 생산을 담당합니다.' },
    ],
    info: [
      { label: '회사명', value: '주식회사 솔컨 (SOLKERN Co., Ltd.)' },
      { label: 'CEO', value: '박진태' },
      { label: '설립', value: '2026년 8월' },
      { label: '업종', value: '식품 도소매 · 원료 R&D · 정보통신(앱 개발)' },
      { label: '소재지', value: '인천광역시 서구 중봉대로612번길 10-20, 5층 505-제이341호 (청라동, 청라프라자)' },
      { label: '이메일', value: 'solkern@solkern.kr' },
    ],
    founderQuote: { quote: '오늘 우리가 만들고 포장한 제품을 내일 아이가 먹습니다. 어쩌면 내 아들이나 손자일지도 모릅니다. 그래서 우리 모두는 제품을 만들 때 자신과 자녀를 생각합니다.', who: 'Valijon Salixov · ERMÁK 창립자' },
  },
  origin: {
    hero: { eyebrow: 'ORIGIN', title: 'The Land Makes the Ingredient', body: '햇빛, 토양, 기후, 그리고 오랜 과수 문화. 좋은 제품은 좋은 원물에서 시작됩니다.' },
    chapters: [
      { num: '01', title: '햇빛', body: '우즈베키스탄은 연중 맑은 날이 많은 대륙성 기후 지역입니다. 길고 강한 일조는 과일의 색과 향을 만드는 가장 중요한 조건입니다.', placeholder: 'ORIGIN-SUN', note: '페르가나 분지 과수원 위로 떠오르는 아침 햇살, 역광의 석류나무' },
      { num: '02', title: '토양과 물', body: '톈산 산맥에서 흘러내린 물과 오아시스 농업의 전통. 건조한 대륙 한가운데서 과일이 자라는 이유입니다.', placeholder: 'ORIGIN-SOIL', note: '관개수로와 붉은 흙, 손에 담긴 흙과 살구' },
      { num: '03', title: '과수 문화', body: '실크로드 시대부터 이어진 과수 재배와 건조 기술. 살구·석류·포도·멜론은 이 땅의 일상이자 문화입니다.', placeholder: 'ORIGIN-CULTURE', note: '지붕 위에서 살구를 말리는 풍경, 시장의 견과 더미' },
      { num: '04', title: '제조', body: 'ERMÁK은 1992년부터 우즈베키스탄에서 자연 식품을 만들어 온 브랜드입니다. 원물의 계절을 따라 착즙·건조·로스팅합니다.', placeholder: 'ORIGIN-FACTORY', note: '깨끗한 생산 라인, 스테인리스 착즙 설비와 유리병 충전' },
    ],
    regions: [
      { name: '페르가나 분지', desc: '우즈베키스탄 최대의 과수 지대. 살구·체리·석류·포도가 자랍니다.', crops: ['살구', '체리', '석류', '포도'] },
      { name: '타슈켄트 · 지자흐', desc: 'ERMÁK 생산 거점. 해바라기씨·견과 가공과 발효유 스낵 생산.', crops: ['해바라기씨', '견과', '쿠르트'] },
      { name: '사마르칸트 · 부하라', desc: '건조 과일과 견과 교역의 오랜 중심지.', crops: ['건살구', '건포도', '아몬드'] },
      { name: '튀르키예', desc: '헤이즐넛·무화과·살구·석류 등 과일 원료와 부산물의 제2 원산지.', crops: ['헤이즐넛', '무화과', '석류', '살구'] },
    ],
    turkiye: { title: '두 번째 원산지, 튀르키예', body: '지중해와 아나톨리아 고원의 과일 원료는 SOLKERN 원료 사업의 두 번째 축입니다. 우즈베키스탄과 튀르키예 원료를 함께 검토하여 계절·품종·물량의 안정성을 확보합니다.', placeholder: 'ORIGIN-TURKIYE' },
    disclaimer: '※ 원산지 서술은 지역 일반 정보에 근거하며, 타국 대비 우수성·성분 비교 등 시험이 필요한 표현은 데이터 확보 후 Data-backed Story로 확장합니다.',
  },
  ermak: {
    hero: { eyebrow: 'ERMÁK · SINCE 1992', title: 'ERMÁK, The Taste You Trust', body: '1992년부터 이어진 ERMÁK의 제품을 SOLKERN이 아시아 시장에 소개합니다. ‘에르막’은 우즈벡어로 즐거움·여유로운 시간을 뜻합니다.' },
    brandStory: {
      title: '우즈베키스탄 건강 간식의 선구자',
      body: '2008년 우즈베키스탄 최초로 해바라기씨를 공장에서 가공·포장하고 전통 발효유 쿠르트를 공장 생산한 브랜드. 타슈켄트·지자흐 생산 거점에서 8개 카테고리 제품을 만들며, 주스 브랜드 ASIL을 함께 운영합니다.',
      facts: [
        { value: '1992', label: '창립' },
        { value: '850+', label: '임직원' },
        { value: '8', label: '제품 카테고리' },
        { value: '4', label: '국제 인증 (ISO 9001·14001·22000·HALAL)' },
      ],
    },
    newProducts: { badge: 'NEW 2026/27', title: '코키 · Challpak — The Third State of Fruit', body: '생과일(1st)도, 건과일(2nd)도 아닌 세 번째 상태. 완숙 살구·감·대추야자를 퓨레로 만들어 부드럽게 말린 코키와 살구·체리 과일 레더 Challpak이 2026/27 카탈로그에 새로 추가되었습니다.', cta: '과일 스낵 보기' },
    categoriesTitle: 'ERMÁK · ASIL 제품 카테고리',
    categories: [
      {
        id: 'juice', name: '주스 · 넥타', en: 'JUICES & NECTARS', brand: 'ASIL',
        desc: '사과, 모과, 석류, 사과·비트, 체리, 살구. 직접 압착 주스와 과즙 넥타 라인.',
        point: '원물 스토리와 가장 직접적으로 연결되는 히어로 카테고리', cover: '/images/bg/splash-pom.webp',
        products: [
          { id: 'j1', name: '석류 주스', sub: 'ASIL marjon · 냉압착', image: '/images/products/juice-pom.webp', sizes: '250ml · 640ml · 1L' },
          { id: 'j2', name: '사과 주스', sub: 'ASIL yashil · 냉압착', image: '/images/products/juice-apple.webp', sizes: '250ml · 640ml · 1L' },
          { id: 'j3', name: '모과 주스', sub: 'ASIL malla · 냉압착', image: '/images/products/juice-quince.webp', sizes: '250ml · 640ml · 1L' },
          { id: 'j4', name: '체리 주스', sub: 'ASIL alvon', image: '/images/products/juice-cherry.webp', sizes: '250ml · 640ml · 1L' },
          { id: 'j5', name: '살구 넥타', sub: 'ASIL tillo', image: '/images/products/juice-apricot.webp', sizes: '250ml · 640ml · 1L' },
          { id: 'j6', name: '사과·비트 주스', sub: 'ASIL zarhal', image: '/images/products/juice-applebeet.webp', sizes: '250ml · 640ml · 1L' },
        ],
      },
      {
        id: 'paste', name: '너트버터 · 페이스트', en: 'NUT BUTTERS & PASTES', brand: 'ERMÁK',
        desc: '땅콩, 캐슈, 참깨(타히니) 페이스트와 대추야자 콘피튀르.',
        point: '자연주의 스프레드 포지션 · 브런치·베이커리 B2B 확장', cover: '/images/bg/pb-toast.webp',
        products: [
          { id: 'p1', name: '땅콩 버터', sub: "Yeryong'oq Pastasi", image: '/images/products/paste-peanut.webp', sizes: '235g · 30g' },
          { id: 'p2', name: '캐슈 버터', sub: 'Kaju Pastasi', image: '/images/products/paste-cashew.webp', sizes: '240g · 30g' },
          { id: 'p3', name: '참깨 페이스트(타히니)', sub: 'Kunjut Pastasi', image: '/images/products/paste-sesame.webp', sizes: '210g · 30g' },
          { id: 'p4', name: '대추야자 콘피튀르', sub: 'Xurmo Konfityuri', image: '/images/products/confiture-date.webp', sizes: '235g' },
        ],
      },
      {
        id: 'jam', name: '잼 · 콘피튀르 · 소스', en: 'JAMS & SAUCES', brand: 'ERMÁK',
        desc: '석류, 포도, 체리, 살구, 대추야자, 모과 잼과 석류·체리 소스.',
        point: '요거트·브런치·베이커리·외식 B2B 확장 가능', cover: '/images/bg/date-drizzle.webp',
        products: [
          { id: 'm1', name: '석류 잼', sub: 'Anor Jemi', image: '/images/products/jam-pom.webp', sizes: '40g · 265g' },
          { id: 'm2', name: '포도 잼', sub: 'Uzum Jemi', image: '/images/products/jam-grape.webp', sizes: '35g · 265g' },
          { id: 'm3', name: '체리 · 살구 · 모과 잼', sub: 'Olcha · O‘rik · Behi Jemi', placeholder: 'PROD-JAM-TRIO', sizes: '35~40g' },
          { id: 'm4', name: '체리 소스 · 석류 소스', sub: 'Olcha Sousi · Anor Sousi', image: '/images/products/sauce-set.webp', sizes: '330g · 340g' },
        ],
      },
      {
        id: 'seeds', name: '해바라기씨 · 씨앗류', en: 'SUNFLOWER SEEDS', brand: 'ERMÁK',
        desc: '검은·흰 해바라기씨(소금/무염/볶음). 소포장부터 2kg 대용량까지.',
        point: '소포장 / 대용량 양방향 운영 · 창고형 매장 후보', cover: '/images/bg/seeds-bowl.webp',
        products: [
          { id: 's1', name: '검은 해바라기씨', sub: 'Qora Pista', image: '/images/products/seeds-black.webp', sizes: '100g · 150g · 200g' },
          { id: 's2', name: '흰 해바라기씨', sub: 'Oq Pista', image: '/images/products/seeds-white.webp', sizes: '100g · 150g · 200g' },
          { id: 's3', name: '볶은 해바라기씨 대용량', sub: 'Qovurilgan Pista', image: '/images/products/seeds-2kg.webp', sizes: '2kg' },
        ],
      },
      {
        id: 'nuts', name: '견과류', en: 'NUTS', brand: 'ERMÁK',
        desc: '아몬드, 캐슈, 피스타치오, 땅콩, 해바라기씨 알맹이, 호박씨, 믹스넛, 견과·건과일 믹스.',
        point: '간편 건강 간식 · 온라인 테스트 SKU 후보', cover: '/images/bg/pistachio.webp',
        products: [
          { id: 'n1', name: '아몬드', sub: 'Bodom', image: '/images/products/nuts-almond.webp', sizes: '40g' },
          { id: 'n2', name: '캐슈넛', sub: 'Kaju', image: '/images/products/nuts-cashew2.webp', sizes: '40g' },
          { id: 'n3', name: '해바라기씨 알맹이', sub: "Pista Mag'zi", image: '/images/products/nuts-pistachio.webp', sizes: '55g' },
          { id: 'n4', name: '견과 믹스', sub: 'Mix · Premium Mix', image: '/images/products/mix-nuts.webp', sizes: '45g' },
          { id: 'n5', name: '소금 견과 믹스', sub: 'Tuzli Mix', image: '/images/products/nuts-mix-salted.webp', sizes: '45g' },
          { id: 'n6', name: '견과·건과일 믹스', sub: 'Nut & Dried Fruit Mix', image: '/images/products/mix-nut-fruit.webp', sizes: '45g' },
          { id: 'n7', name: '소금 호박씨(껍질)', sub: "Qovoq Urug'i", image: '/images/products/seeds-pumpkin.webp', sizes: '40g' },
        ],
      },
      {
        id: 'qurt', name: '쿠르트 · 발효유 스낵', en: 'QURT & DAIRY SNACKS', brand: 'ERMÁK',
        desc: '중앙아시아 전통 건조 발효유 쿠르트, 비오쿠르트, 쿠르토바·아이란 음료.',
        point: '중앙아시아 대표성이 강한 카테고리 · 소비자 교육형 도입', cover: '/images/bg/qurt-splash.webp',
        products: [
          { id: 'q1', name: '비오쿠르트', sub: 'Bioqurt', image: '/images/products/qurt-pack.webp', sizes: '30g · 47g · 60g' },
          { id: 'q2', name: '쿠르트 (볼)', sub: 'Qurt', image: '/images/products/qurt-ball.webp', sizes: '30g · 47g · 60g' },
          { id: 'q3', name: '매운 고추 쿠르트', sub: 'Achchiq Qurt', image: '/images/products/qurt-hot.webp', sizes: '30g · 47g' },
          { id: 'q8', name: '단단한 쿠르트', sub: 'Toshqurt', image: '/images/products/qurt-tosh.webp', sizes: '25g · 42g' },
          { id: 'q6', name: '바질 쿠르트', sub: 'Rayhonlik Qurt', image: '/images/products/qurt-basil.webp', sizes: '30g · 47g · 60g' },
          { id: 'q7', name: '사각 바질 쿠르트', sub: 'Square-shaped Qurt with Basil', image: '/images/products/qurt-square.webp', sizes: '30g · 47g · 60g' },
          { id: 'q4', name: '쿠르토바', sub: 'Qurtoba', image: '/images/products/qurtoba-cup.webp', sizes: '250ml · 400ml' },
          { id: 'q5', name: '바질 아이란', sub: 'Ayron Rayhonli', image: '/images/products/ayron-cup.webp', sizes: '250ml · 400ml' },
        ],
      },
      {
        id: 'bar', name: '내추럴 넛바', en: 'NATURAL NUT BARS', brand: 'ERMÁK',
        desc: '호박씨, 아몬드, 참깨, 믹스넛, 땅콩, 해바라기씨 바.',
        point: '간편 건강 간식 · 온라인 테스트 SKU 후보', cover: '/images/bg/seedbar.webp',
        products: [
          { id: 'b1', name: '호박씨 바', sub: "Qovoq Urug'i", image: '/images/products/bar-pumpkin.webp', sizes: '30~38g' },
          { id: 'b2', name: '아몬드 바', sub: 'Bodom', image: '/images/products/bar-almond.webp', sizes: '30~38g' },
          { id: 'b3', name: '참깨 · 해바라기씨 바', sub: 'Kunjut · Kungaboqar', image: '/images/products/bar-sesame.webp', sizes: '30~38g' },
        ],
      },
      {
        id: 'snack', name: '과일 스낵 코키 · Challpak', en: 'FRUIT SNACKS — QOQI & CHALLPAK', brand: 'ERMÁK',
        desc: '2026/27 신제품. 살구·감·대추야자를 퓨레로 만들어 부드럽게 말린 코키, 살구·체리 과일 레더 Challpak. “과일의 세 번째 상태(The Third State of Fruit)”.',
        point: '한국 소비자에게 가장 새로운 포맷 · 온라인 테스트 SKU 1순위', cover: '/images/bg/snack-lineup.webp',
        products: [
          { id: 'o4', name: '살구 코키', sub: "O'rik QOQI · NEW", image: '/images/products/qoqi-apricot.webp', sizes: '25g×10 · 대용량 25g×50' },
          { id: 'o5', name: '감 코키', sub: 'Xurmo QOQI · NEW', image: '/images/products/qoqi-persimmon.webp', sizes: '25g×10 · 대용량 25g×50' },
          { id: 'o6', name: '아즈와 대추야자 코키', sub: 'Ajwa Xurmo QOQI · NEW', image: '/images/products/qoqi-date.webp', sizes: '17g×10 · 대용량 17g×50' },
          { id: 'o7', name: '살구 Challpak (바르가크)', sub: "O'rik Challpak · Bargak · NEW", image: '/images/products/challpak-apricot-bargak.webp', sizes: '18g×14 · 대용량 18g×60' },
          { id: 'o8', name: '살구 Challpak (칸텍)', sub: "O'rik Challpak · Kantek · NEW", image: '/images/products/challpak-apricot-kantek.webp', sizes: '18g×14 · 대용량 18g×60' },
          { id: 'o9', name: '체리 Challpak', sub: 'Olcha Challpak · NEW', image: '/images/products/challpak-cherry.webp', sizes: '23g×14 · 대용량 23g×60' },
          { id: 'o10', name: '코키 대용량 (살구)', sub: "O'rik QOQI Large Pack", image: '/images/products/qoqi-apricot-large.webp', sizes: '25g×50' },
          { id: 'o11', name: 'Challpak 대용량 (체리)', sub: 'Olcha Challpak Large Pack', image: '/images/products/challpak-cherry-large.webp', sizes: '23g×60' },
        ],
      },
      {
        id: 'other', name: '링 크래커 · 퓨레', en: 'DRY BREAD RINGS & PUREE', brand: 'ERMÁK',
        desc: '드라이 브레드 링(테식 쿨차·수쉬키) 3종과 사과·살구·모과 과일 퓨레.',
        point: '현지성 강한 라인 · 2차 또는 테스트 라인', cover: '/images/bg/rings.webp',
        products: [
          { id: 'o1', name: '소금 링 크래커', sub: 'Teshik Kulcha · Tuzli', image: '/images/products/rings-pack.webp', sizes: '50g · 100g' },
          { id: 'o2', name: '스테비아·흰참깨 링 크래커', sub: 'Shirin Kunjutli Teshik Kulcha', image: '/images/products/rings-stevia.webp', sizes: '50g · 100g' },
          { id: 'o3', name: '흰참깨·블랙커민 링 크래커', sub: 'Kunjut va Qora Sedanali', image: '/images/products/rings-sesame.webp', sizes: '50g · 100g' },
          { id: 'o12', name: '과일 퓨레', sub: 'Olma · O‘rik · Behi Pyuresi', placeholder: 'PROD-PUREE', sizes: '175g' },
        ],
      },
    ],
    korea: {
      title: 'Korea Launch Roadmap',
      body: '한국 런칭은 채널별 적합 품목부터 단계적으로 진행합니다.',
      phases: [
        { phase: 'PHASE 1', items: '씨앗·견과 · 잼·페이스트 · 건과일', channel: '온라인 공식 브랜드숍 · 소포장 채널' },
        { phase: 'PHASE 2', items: 'ASIL 주스 6종 · 소스', channel: '창고형 매장 · 외식·카페 B2B' },
        { phase: 'PHASE 3', items: '쿠르트 · 발효유 음료', channel: '축산물 수입 요건 확인 후 도입' },
      ],
    },
    cta: { title: '전체 제품 카탈로그가 필요하신가요?', body: 'ERMÁK 2026/27 · ASIL 카탈로그와 품목별 규격서를 보내드립니다.', button: '카탈로그 요청' },
  },
  materialLab: {
    hero: { eyebrow: 'MATERIAL LAB · PROJECT 2', title: 'Nothing Ends at the Factory', body: '제조 공정 후 남은 껍질과 씨앗, 박까지 새로운 식품·소재 가치로 전환합니다.' },
    thesis: { title: '가장 큰 가치는 분말이 아니라 “규격화된 원료”에 있습니다', body: '버려지던 부산물을 깨끗하게, 균일하게, 서류를 갖춰 공급하는 것. SOLKERN MATERIAL LAB은 기술이 아니라 품질 보증과 균일성으로 가치를 만듭니다.' },
    tracks: [
      { id: 'beauty', title: '뷰티 소재', en: 'BEAUTY', body: '석류껍질 복합추출물(폴리페놀 표준화)과 과일 씨앗·껍질 천연 스크럽 파우더. 입도별 설계로 피부 타입에 맞는 강도를 제안합니다.', materials: ['석류껍질 추출물', '석류씨 · 체리씨 · 살구씨 파우더', '호두껍질 · 포도씨 파우더'], stage: '원료 확보 · 1차 발주 진행', placeholder: 'LAB-BEAUTY' },
      { id: 'food', title: '식품 소재', en: 'FOOD', body: '과육·곡물 분말 기반 RTE/RTD 쉐이크와 사과박 파이버. 식품 원료 인정 트랙을 병행하여 사용 가능한 원료부터 상품화합니다.', materials: ['과육 분말(석류·체리·살구·사과 등)', '곡물 분말', '착즙박 식이섬유'], stage: '레시피 개발 · 타당성 검토', placeholder: 'LAB-FOOD' },
      { id: 'ingredient', title: '산업 소재', en: 'INGREDIENT', body: '호두껍질 등 견과 부산물의 메쉬 등급별 연마재·필러 용도. 규격서와 성적서를 갖춘 B2B 원료로 공급합니다.', materials: ['호두껍질 연마재', '견과 부산물 필러', '규격화 분말'], stage: '원료 소싱 검토', placeholder: 'LAB-INDUSTRY' },
    ],
    process: [
      { step: '01', title: '원료 확보', desc: '우즈베키스탄·튀르키예 현지 부산물 수급, 동결건조·분말화' },
      { step: '02', title: '분석', desc: '성분 분석, 잔류농약·중금속 등 안전성 시험, COA 확보' },
      { step: '03', title: '규제 검토', desc: '식품공전·화장품 원료 기준 등 사용 가능 범위 사전 확인' },
      { step: '04', title: '2차 가공', desc: '한국에서 추출·분획·입도 설계·규격화' },
      { step: '05', title: '상품화 · B2B', desc: '원료 공급, OEM/ODM 상품 개발, 파트너 협업' },
    ],
    principles: [
      { title: '규제가 먼저', desc: '사용 가능 여부와 인정 트랙을 먼저 확인하고 투자합니다.' },
      { title: '데이터로 말하기', desc: '검증 전 효능·비교 표현은 쓰지 않습니다. 성적서와 규격서로 제안합니다.' },
      { title: '잔사도 자원', desc: '추출 후 남는 펙틴·식이섬유까지 부수입원으로 설계합니다.' },
    ],
    cta: { title: '원료 협업을 제안해 주세요', body: '부산물 공급, 공동 R&D, 원료 구매, OEM/ODM 등 어떤 형태의 협업도 환영합니다.', button: '원료 협업 문의' },
  },
  b2b: {
    hero: { eyebrow: 'B2B', title: 'Partner with SOLKERN', body: '완제품 유통, 원료 공급, OEM/ODM, 한국 2차 가공 및 아시아 시장 협업을 제안합니다.' },
    services: [
      { id: 'dist', title: '완제품 유통', desc: 'ERMÁK · ASIL 완제품의 국내·아시아 유통 파트너십', bullets: ['창고형 매장 · 대형 유통 납품', '온라인 채널 공급', '외식·카페·베이커리 B2B', '아시아 국가별 파트너 협의'] },
      { id: 'raw', title: '원료 공급', desc: '과일 원료·분말·부산물의 규격 공급', bullets: ['과육·과피·씨앗 분말', '동결건조 원료', 'COA·규격서 동반', 'MOQ · 리드타임 협의'] },
      { id: 'oem', title: 'OEM / ODM', desc: '한국 2차 가공을 통한 상품 개발', bullets: ['쉐이크·스프레드 등 식품 상품 개발', '스크럽·추출물 등 뷰티 원료', '패키지·라벨 검토 지원', '소량 파일럿 생산 협의'] },
      { id: 'sample', title: '샘플 · 자료 요청', desc: '제품 샘플과 품질 서류 제공', bullets: ['제품 카탈로그(ERMÁK · ASIL)', '품목별 규격서', '시험성적서(COA) · 인증서', '샘플 발송 협의'] },
    ],
    steps: [
      { step: '01', title: '문의 접수', desc: 'Contact 폼 또는 이메일로 관심 품목·용도·수량을 알려주세요.' },
      { step: '02', title: '자료 · 샘플', desc: '카탈로그, 규격서, COA, 샘플을 제공합니다.' },
      { step: '03', title: '조건 협의', desc: '가격, MOQ, 리드타임, 인코텀즈, 결제 조건을 협의합니다.' },
      { step: '04', title: '계약 · 공급', desc: '계약 체결 후 수입·통관·국내 물류를 거쳐 공급합니다.' },
    ],
    docs: ['제품 카탈로그', '품목별 규격서(Spec Sheet)', '시험성적서(COA)', 'ISO · HALAL 인증서', '원산지 증명서', '라벨 표시 사항'],
    faq: [
      { q: '최소 주문 수량(MOQ)은 어떻게 되나요?', a: '품목·포장 단위에 따라 다릅니다. 문의 시 희망 수량을 알려주시면 품목별 MOQ와 리드타임을 안내드립니다.' },
      { q: '샘플을 받을 수 있나요?', a: '가능합니다. B2B 문의 후 샘플 품목과 수량을 협의하며, 배송비는 사전 협의합니다.' },
      { q: '원료(부산물)도 소량 구매가 가능한가요?', a: 'R&D 용도의 소량 샘플 구매를 지원합니다. 규격과 시험성적서를 함께 제공합니다.' },
      { q: '한국 외 국가로도 공급하나요?', a: '네. ERMÁK 총판 계약상 판권 지역인 아시아·태평양 12개국(한국·중국·일본·대만·홍콩·몽골·베트남·태국·말레이시아·인도네시아·필리핀·호주)의 파트너와 협의합니다. 중앙아시아 5개국은 ERMÁK 본사가 직접 관리합니다.' },
    ],
    cta: { title: '지금 B2B 상담을 시작하세요', button: 'B2B 문의하기' },
  },
  news: {
    hero: { eyebrow: 'NEWS', title: 'SOLKERN Journal', body: '출장, 계약, 런칭, 전시, R&D 진행 소식을 전합니다.' },
    empty: '등록된 소식이 없습니다.',
    items: [
      { id: 'n-2026-09-01', date: '2026.09', category: 'R&D', title: '석류껍질 분말 1차 100kg 동결건조 원료 발주', summary: '석류껍질 추출물 원료 사업의 첫 단계로 동결건조 분말 100kg을 발주했습니다. 분석·규격화 작업을 시작합니다.', placeholder: 'NEWS-POMEGRANATE' },
      { id: 'n-2026-08-01', date: '2026.08', category: 'COMPANY', title: '㈜솔컨 법인 설립', summary: '인천 청라에 ㈜솔컨을 설립했습니다. ERMÁK 완제품 유통과 원료 R&D 사업을 본격화합니다.', placeholder: 'NEWS-OFFICE' },
      { id: 'n-2026-06-01', date: '2026.06', category: 'PRODUCT', title: 'ERMÁK · ASIL 한국어 카탈로그 발행', summary: 'ERMÁK 8개 카테고리와 ASIL 주스 6종·소스 2종의 한국어 카탈로그를 발행했습니다.', placeholder: 'NEWS-CATALOG' },
    ],
  },
  contact: {
    hero: { eyebrow: 'CONTACT', title: 'Partner with SOLKERN', body: '완제품 유통, 원료 공급, OEM/ODM, 한국 및 아시아 시장 협업을 제안해 주세요. 영업일 기준 2일 내 회신드립니다.' },
    form: {
      name: '담당자 성함', company: '회사명', email: '이메일', phone: '연락처', country: '국가 / 지역',
      type: '문의 유형', typeOptions: ['완제품 유통', '원료 공급', 'OEM / ODM', '샘플 · 카탈로그 요청', '원료 협업 · R&D', '기타'],
      product: '관심 품목 / 원료', quantity: '예상 수량 · MOQ', message: '문의 내용',
      agree: '개인정보 수집·이용에 동의합니다 (문의 회신 목적, 보관 1년)', submit: '문의 보내기',
      success: '문의가 접수되었습니다', successBody: '담당자가 확인 후 이메일 또는 연락처로 회신드리겠습니다.',
      privacy: '수집 항목: 성함, 회사명, 이메일, 연락처, 문의 내용 · 이용 목적: 문의 회신 · 보관 기간: 1년',
    },
    info: [
      { label: 'EMAIL', value: 'solkern@solkern.kr', href: 'mailto:solkern@solkern.kr' },
      { label: 'TEL', value: '010-4589-1030', href: 'tel:01045891030' },
      { label: 'WEB', value: 'www.solkern.kr', href: 'https://www.solkern.kr' },
    ],
    officeTitle: 'OFFICE',
    address: '인천광역시 서구 중봉대로612번길 10-20, 5층 505-제이341호 (청라동, 청라프라자)',
  },
  territory: {
    eyebrow: 'DISTRIBUTION TERRITORY',
    title: 'Asia-Pacific 12 Markets',
    body: 'ERMÁK 총판 계약에 따라 한국을 거점으로 동북아·동남아·오세아니아 12개국에 ERMÁK 완제품을 공급합니다.',
    countLabel: '판권 국가',
    regions: [
      { name: '동북아시아', countries: [
        { code: 'KR', name: '한국', city: '인천 · 운영 거점' },
        { code: 'CN', name: '중국', city: '베이징' },
        { code: 'JP', name: '일본', city: '도쿄' },
        { code: 'TW', name: '대만', city: '타이베이' },
        { code: 'HK', name: '홍콩', city: '홍콩' },
        { code: 'MN', name: '몽골', city: '울란바토르' },
      ] },
      { name: '동남아시아', countries: [
        { code: 'VN', name: '베트남', city: '하노이' },
        { code: 'TH', name: '태국', city: '방콕' },
        { code: 'MY', name: '말레이시아', city: '쿠알라룸푸르' },
        { code: 'ID', name: '인도네시아', city: '자카르타' },
        { code: 'PH', name: '필리핀', city: '마닐라' },
      ] },
      { name: '오세아니아', countries: [{ code: 'AU', name: '호주', city: '시드니' }] },
    ],
    origins: [
      { code: 'UZ', name: '우즈베키스탄', role: 'ERMÁK 생산 · 원산지' },
      { code: 'TR', name: '튀르키예', role: '과일 원료 · 부산물' },
    ],
    hub: '운영 거점',
    legendTerritory: '판권 12개국',
    legendOrigin: '원산지',
    legendDirect: '중앙아시아 (ERMÁK 본사 직접 관리)',
    note: '※ ERMÁK 총판 계약 기준 판권 지역입니다. 중앙아시아 5개국(카자흐스탄·키르기스스탄·타지키스탄·투르크메니스탄·우즈베키스탄)은 ERMÁK 본사가 직접 관리합니다. 국가별 공급 조건은 B2B 문의로 안내드립니다.',
    tapHint: '국가를 누르면 지도에서 강조됩니다',
  },
  ui: {
    langName: '한국어',
    sections: { solkernBusiness: '세 개의 비즈니스, 하나의 흐름', solkernPartners: '생산에서 판매까지, 3사 협력 구조', companyInfo: '회사 정보', originRegions: '원물이 자라는 곳', labTracks: '세 가지 소재 트랙', labProcess: '부산물에서 규격 원료까지', b2bServices: '협력 방식', b2bProcess: '문의부터 공급까지', b2bFaq: '자주 묻는 질문' },
    originMarquee: ['햇빛', '토양', '기후', '과수 문화', '우즈베키스탄', '튀르키예', '석류', '살구', '체리', '견과'],
    table: { region: '권역', country: '국가', city: '주요 도시' },
    regionsLabel: '권역', originsLabel: '원산지',
    prev: '이전 제품', next: '다음 제품',
    productNote: '※ 제품 규격·표시 사항은 수입 라벨 기준으로 확정되며, 카탈로그 요청 시 품목별 규격서를 제공합니다.',
    countryPlaceholder: '대한민국',
    privacy: {
      title: '개인정보처리방침',
      intro: '주식회사 솔컨(이하 "회사")은 홈페이지 문의 접수를 위해 아래와 같이 개인정보를 수집·이용합니다.',
      items: ['수집 항목: 성함, 회사명, 이메일, 연락처, 국가, 문의 내용', '수집 목적: 문의 회신, 견적·샘플·자료 제공', '보관 기간: 접수일로부터 1년 (관계 법령에 따라 보관이 필요한 경우 해당 기간)', '제3자 제공: 없음 (법령에 따른 경우 제외)'],
      officer: '개인정보 보호책임자: 박진태',
    },
  },
  footer: {
    tagline: 'From Origin to New Value',
    company: '주식회사 솔컨 SOLKERN Co., Ltd.',
    ceo: '정보관리책임자 박진태',
    regNo: '사업자등록번호 443-86-03703',
    address: '인천광역시 서구 중봉대로612번길 10-20, 5층 505-제이341호 (청라동, 청라프라자)',
    email: 'solkern@solkern.kr',
    tel: '010-4589-1030',
    copyright: '© 2026 SOLKERN Co., Ltd. All rights reserved.',
    links: [
      { label: '개인정보처리방침', href: '/privacy' },
      { label: '관리자', href: '/admin' },
    ],
  },
};
