import type { Dict } from './types';
import { ko } from './ko';

// Türkçe metin otomatik çeviri taslağıdır — yayın öncesi ana dili Türkçe olan birinin gözden geçirmesi önerilir.
export const tr: Dict = {
  meta: {
    title: 'SOLKERN | From Origin to New Value — Özbekistan ve Türkiye’den doğal gıdalar ve hammadde Ar-Ge’si',
    description:
      'SOLKERN, Özbekistan ve Türkiye’nin doğal gıda markaları ERMÁK ve ASIL’in ürünlerini Asya pazarlarına tanıtır; meyve hammaddelerini ve yan ürünlerini Kore işleme teknolojisiyle yeni hammaddelere dönüştürür.',
  },
  nav: ko.nav,
  common: {
    more: 'Daha fazla', contact: 'İletişime geçin', catalog: 'Katalog isteyin', b2b: 'B2B görüşmesi',
    viewProducts: 'ERMÁK ürünlerini inceleyin', viewMaterial: 'Hammadde ve B2B', scroll: 'SCROLL', langLabel: 'Dil',
    readMore: 'Devamını okuyun', back: 'Listeye dön', send: 'Gönder', sending: 'Gönderiliyor…', sent: 'Gönderildi',
    error: 'Gönderilemedi. Lütfen daha sonra tekrar deneyin.', required: 'zorunlu', officialDistributor: 'ERMÁK’ın Asya’ya ortak açılımında resmî iş ortağı',
  },
  home: {
    hero: {
      eyebrow: 'Quality Without Borders · ERMÁK’ın Asya’ya ortak açılımında resmî iş ortağı · Hammadde Ar-Ge’si',
      title: 'From Origin', titleAccent: 'to New Value',
      body: 'Özbekistan’ın doğasında yetişen meyveler Asya sofralarıyla buluşuyor ve Kore teknolojisiyle bir kez daha değere dönüşüyor.',
      cta1: 'ERMÁK ürünlerini inceleyin', cta2: 'Hammadde ve B2B',
    },
    journey: {
      eyebrow: 'THE SOLKERN WAY',
      title: 'İyi hammaddeyi buluyor, pazarını kuruyor ve geriye kalan değeri yeniden hayata döndürüyoruz.',
      steps: [
        { key: 'origin', label: '01 ORIGIN', title: 'Hammaddenin yetiştiği toprak', body: 'Güçlü güneş, karasal iklim ve köklü bir meyvecilik kültürü. Özbekistan ve Türkiye’nin meyveleri ve kuruyemişleri bir hikâyeyle başlar.' },
        { key: 'product', label: '02 PRODUCT', title: 'ERMÁK ürünleri', body: '1992’den beri üretilen ERMÁK meyve suları, reçelleri, kuruyemiş ezmeleri, çekirdekleri, kurutu ve barları SOLKERN ile Asya pazarına ulaşıyor.' },
        { key: 'second', label: '03 SECOND LIFE', title: 'Fabrikada bitmeyen değer', body: 'Üretimden arta kalan kabuk, çekirdek ve posa, Kore işleme teknolojisiyle gıda, güzellik ve endüstri hammaddesine dönüşür.' },
        { key: 'market', label: '04 MARKET', title: 'Asya dağıtımı ve B2B ağı', body: 'Ürün dağıtımı, hammadde tedariki, OEM/ODM. Kore merkezli olarak Asya’daki ortaklarımızla birlikte pazar kuruyoruz.' },
      ],
    },
    land: {
      eyebrow: '02 · THE LAND', title: 'Why Central Asia, Why Uzbekistan',
      body: 'Güçlü güneş ışığı, karasal iklim ve yüzyıllık meyvecilik kültürü çok çeşitli meyve ve kuruyemiş yetiştirir. İyi ürün, iyi hammaddeyle başlar.',
      facts: [
        { value: '300+', label: 'Yıllık güneşli gün (bölge ortalaması, tahmini)' },
        { value: '1992', label: 'ERMÁK’ın kuruluş yılı' },
        { value: '2', label: 'Ana menşe — Özbekistan · Türkiye' },
        { value: '9', label: 'ERMÁK ürün kategorisi' },
      ],
      cta: 'Menşe hikâyesini okuyun',
    },
    fruit: {
      eyebrow: '03 · THE FRUIT', title: 'One Origin, Many Possibilities',
      body: 'Nar, kayısı, kiraz, elma, üzüm, kuruyemiş. Tek bir hammadde hem ürüne hem de malzemeye dönüşür.',
      items: [
        { name: 'Nar', product: 'Meyve suyu · reçel · sos', material: 'Kabuk ekstresi · çekirdek tozu', image: '/images/custom/FRUIT-POMEGRANATE.webp' },
        { name: 'Elma', product: 'Meyve suyu · püre', material: 'Elma posası lifi', image: '/images/fruits/apple.webp' },
        { name: 'Kiraz', product: 'Meyve suyu · reçel · sos', material: 'Çekirdek peeling tozu', image: '/images/fruits/cherry.webp' },
        { name: 'Kayısı', product: 'QOQI · Challpak · nektar · reçel', material: 'Çekirdek ve kabuk malzemeleri', placeholder: 'FRUIT-APRICOT' },
        { name: 'Kuruyemiş ve çekirdek', product: 'Kuruyemiş ezmesi · bar · kavrulmuş', material: 'Kuruyemiş yan ürünlerinden gıda hammaddesi', placeholder: 'FRUIT-NUTS' },
        { name: 'Üzüm · hurma', product: 'Reçel · konfitür', material: 'Üzüm çekirdeği · kabuk malzemeleri', placeholder: 'FRUIT-GRAPE' },
      ],
      cta: 'Meyveye göre olanakları görün',
    },
    collection: { eyebrow: '04 · ERMÁK COLLECTION', title: 'The Taste You Trust', body: 'Meyve suları ve nektarlar, kuruyemiş ezmeleri, reçel ve soslar, çekirdek ve kuruyemişler, kurut ve barlar — ERMÁK’ın öne çıkan ürün grupları.', cta: 'Ürün kataloğu isteyin' },
    featured: { eyebrow: '05 · FEATURED PRODUCTS', title: 'Korea Launch Priority', body: 'Kore lansmanı; çekirdek ve kuruyemiş, reçel ve ezme, meyve suyu, kurut gibi kanala uygun ürünlerden başlayarak aşamalı ilerler.', cta: 'B2B görüşmesi', tags: ['Çevrimiçi test ürünleri', 'Toptan market büyük boy', 'Yeme-içme ve fırın B2B', 'Küçük paket kanalları'] },
    secondLife: {
      eyebrow: '06 · SECOND LIFE', title: 'Nothing Ends at the Factory',
      body: 'Üretim bitti diye hammaddenin değeri bitmez. Kabuk, çekirdek ve posa, Kore işleme teknolojisiyle yeni malzemelere dönüşür.',
      flow: [
        { label: 'Fabrika yan ürünleri', desc: 'Nar kabuğu · meyve çekirdekleri · posa · kuruyemiş yan ürünleri' },
        { label: 'Birincil işleme', desc: 'Yıkama · (dondurarak) kurutma · öğütme · tane boyutu tasarımı' },
        { label: 'Kore Ar-Ge’si', desc: 'Bileşen analizi · ekstraksiyon · standardizasyon · analiz sertifikası' },
        { label: 'Yeni malzemeler', desc: 'Gıda · güzellik · endüstri için B2B tedarik' },
      ],
      cta: 'MATERIAL LAB’ı görün',
    },
    material: {
      eyebrow: '07 · MATERIAL VALUE', title: 'Food · Beauty · Ingredient',
      body: 'Elma posası life, nar kabuğu kozmetik ekstresine, kuruyemiş yan ürünleri gıda hammaddesine dönüşebilir.',
      cards: [
        { title: 'FOOD', from: 'Meyve ve tahıl tozları', to: 'RTE/RTD shake · diyet lifi', desc: 'Özbek meyve tozlarının Kore reçeteleriyle ürünleştirilmesi', placeholder: 'MAT-FOOD' },
        { title: 'BEAUTY', from: 'Nar kabuğu · meyve çekirdekleri', to: 'Ekstreler · doğal peeling tozları', desc: 'Polifenol standardize ekstreler ve tane boyutuna göre peeling hammaddeleri', placeholder: 'MAT-BEAUTY' },
        { title: 'INGREDIENT', from: 'Posa · kuruyemiş kabukları', to: 'Lif · endüstriyel malzemeler', desc: 'Standardize tozlar ve eksiksiz belgelerle B2B hammadde', placeholder: 'MAT-INGREDIENT' },
      ],
      cta: 'Hammadde iş birliği',
    },
    market: {
      eyebrow: '08 · MARKET', title: 'Asia Distribution & B2B Network',
      body: 'SOLKERN, Kore merkezinden ERMÁK ürünlerini Asya-Pasifik’teki 12 pazara dağıtır ve Kore’de ikincil işleme malzeme işini birlikte yürütür.',
      nodes: [
        { name: 'UZBEKISTAN', role: 'Hammadde · ERMÁK üretimi' },
        { name: 'TÜRKİYE', role: 'Meyve hammaddeleri · yan ürünler' },
        { name: 'KOREA', role: 'SOLKERN Ar-Ge · işleme · dağıtım' },
        { name: 'ASIA-PACIFIC 12', role: '12 pazarda ürün ve hammadde B2B' },
      ],
      cta: 'Ortaklık görüşmesi',
    },
    trust: {
      eyebrow: '09 · TRUST', title: 'Data-backed Origin Story',
      body: 'Yalnızca analiz verileri, sertifikalar, ithalat standartları ve kalite belgeleriyle desteklenen hammadde ve ürünleri öneriyoruz.',
      items: [
        { title: 'Analiz sertifikası (COA)', desc: 'Pestisit kalıntısı, ağır metal, mikrobiyoloji gibi güvenlik test raporlarına dayalı teklif' },
        { title: 'İthalat standardı incelemesi', desc: 'Kore Gıda Kodeksi ve ithal gıda güvenliği kurallarına göre ürün bazında ön inceleme' },
        { title: 'Etiket doğrulaması', desc: 'Yalnızca doğrulanmış ifadeler kullanılır; doğrulanmamış ifadelere yer verilmez' },
        { title: 'Sertifikalı üretim', desc: 'ISO 9001 · ISO 14001 · ISO 22000 (HACCP) · HALAL sertifikalı üretici şirketler' },
      ],
      certs: ['ISO 9001:2015', 'ISO 14001:2015', 'ISO 22000:2018 (HACCP)', 'HALAL UAE.S GSO 2055-1'],
      cta: 'Kalite belgelerini isteyin',
      note: '* Sertifikalar ERMÁK üretici şirketlerine (ERMAKPLUS LLC · ZAFARHON LLC) aittir; ürün bazındaki kapsam talep üzerine teyit edilir.',
    },
    contact: { eyebrow: '10 · CONTACT', title: 'Partner with SOLKERN', body: 'Ürün dağıtımı, hammadde tedariki, OEM/ODM veya Kore ve Asya pazarlarında iş birliği için bize teklifinizi iletin.', cta1: 'İletişime geçin', cta2: 'Katalog isteyin' },
    daily: {
      eyebrow: 'SOLKERN DAILY',
      title: 'Günlük hayatta ERMÁK',
      body: 'Kahvaltı sofrasından öğleden sonraki bir bardağa — Özbekistan’ın meyvelerinin Kore’de bir güne karıştığı anlar.',
      captions: ['Sabah · fıstık ezmeli tost', 'Öğleden sonra · bir bardak nar suyu', 'Çay saati · QOQI meyve atıştırmalığı', 'Brunch · yoğurt ve kiraz reçeli', 'Hafta sonu · yürüyüş ve kuruyemiş barı', 'Kafe · ayran ve kurut'],
    },
    timeline: {
      eyebrow: 'SINCE 1992',
      title: 'Hammaddenin toprağından Kore teknolojisine uzanan zaman',
      items: [
        { year: '1992', title: 'ERMÁK kuruldu', desc: 'Doğal gıda markası ERMÁK, Özbekistan’ın Taşkent şehrinde yola çıktı.' },
        { year: '2008', title: 'Fabrikada işlenen ayçekirdeği · fabrika üretimi kurut', desc: 'Özbekistan’da ayçekirdeğini ilk kez fabrikada işleyip paketleyen ve geleneksel kurutu fabrikada üreten marka oldu.' },
        { year: '2025', title: 'ERMÁK için Asya-Pasifik 12 pazar hakkı', desc: 'CATKIN Co., Ltd., ERMÁK ürünlerinin Asya-Pasifik’teki 12 pazarda dağıtım haklarını aldı.' },
        { year: '2026.06', title: 'ERMÁK · ASIL Korece kataloğu yayımlandı', desc: 'ERMÁK’ın 8 kategorisini ve ASIL’in 6 meyve suyu ile 2 sosunu içeren Korece katalog yayımlandı.' },
        { year: '2026.08', title: 'SOLKERN Co., Ltd. kuruldu', desc: 'Incheon Cheongna’da kurulan SOLKERN, ERMÁK’ın Asya’ya ortak açılımındaki resmî iş ortağı olarak dağıtım ve hammadde Ar-Ge’sine başladı.' },
        { year: '2026.09', title: 'İlk nar kabuğu tozu siparişi', desc: '100 kg dondurularak kurutulmuş nar kabuğu tozu siparişiyle MATERIAL LAB’ın ilk projesi başladı.' },
      ],
    },
  },
  solkern: {
    hero: { eyebrow: 'ABOUT SOLKERN', title: 'İyi hammaddeyi buluyor, pazarını kuruyor ve geriye kalan değeri yeniden hayata döndürüyoruz.', body: 'SOLKERN Co., Ltd., Özbekistan ve Türkiye’nin doğal gıdalarını ve meyve hammaddelerini Kore ve Asya pazarlarına bağlayan bir hammadde, dağıtım ve Ar-Ge şirketidir.' },
    statement: 'Origin → Product → Second Life → Market. Orta Asya hammaddesinden ERMÁK ürünlerine ve Kore’deki ikincil işleme malzeme işine uzanan tek bir akış.',
    identity: [
      { title: 'ERMÁK’ın Asya’ya ortak açılımında resmî iş ortağı', body: '1992’den beri Özbekistan’ın önde gelen doğal gıda markası ERMÁK’ın ve meyve suyu markası ASIL’in ürünlerini Kore başta olmak üzere Asya-Pasifik’teki 12 pazara tanıtıyoruz.' },
      { title: 'Hammadde Ar-Ge’si · Kore’de ikincil işleme', body: 'Meyve hammaddelerini ve üretim yan ürünlerini (kabuk, çekirdek, posa) analiz edip işleyerek ve standardize ederek gıda, güzellik ve endüstri malzemelerine dönüştürüyoruz.' },
      { title: 'Veriyle tamamlanan güven', body: 'Duygu doğadan başlar; B2B güveni ise analiz sertifikaları, belgeler ve ithalat standardı incelemeleriyle tamamlanır.' },
    ],
    business: [
      { title: 'Ürün dağıtımı', desc: 'ERMÁK · ASIL ürünlerinin Kore ve Asya’da dağıtımı', items: ['Resmî çevrimiçi marka mağazası', 'Toptan marketler ve büyük perakende', 'Yeme-içme, fırın ve kafe B2B', 'Asya’daki ortaklarla dağıtım'] },
      { title: 'Hammadde tedariki', desc: 'Özbekistan ve Türkiye’den meyve hammaddeleri, tozlar ve yan ürünler', items: ['Meyve eti, kabuk ve çekirdek tozları', 'Dondurularak kurutulmuş hammaddeler', 'Şartname ve COA ile birlikte tedarik', 'MOQ ve numune görüşülür'] },
      { title: 'Ar-Ge · OEM/ODM', desc: 'Kore’de ikincil işlemeyle malzeme ve ürün geliştirme', items: ['Analiz, ekstraksiyon, standardizasyon', 'Yeni gıda hammaddesi onay süreci', 'Kozmetik hammaddeleri ve peeling tozları', 'OEM/ODM ürün geliştirme'] },
    ],
    partners: [
      { name: 'ZAFARXON · ERMÁK', role: 'Özbekistan’da üretim', desc: 'ERMAKPLUS LLC · ZAFARHON LLC. Taşkent ve Cizzak üretim tesisleri, ISO · HACCP · HALAL sertifikalı hatlar.' },
      { name: 'CATKIN Co., Ltd.', role: 'İthalat ve gümrük ortağı', desc: 'ERMÁK’ın Asya-Pasifik’teki 12 pazarı (Kore, Çin, Japonya, Tayvan, Hong Kong, Moğolistan, Vietnam, Tayland, Malezya, Endonezya, Filipinler, Avustralya) için dağıtım haklarının sahibi. İthalat, gümrük, karantina ve yurt içi depolamayı üstlenir.' },
      { name: 'SOLKERN Co., Ltd.', role: 'Satış · Ar-Ge · OEM/ODM', desc: 'Ürün planlama, pazarlama, kanal yönetimi, hammadde Ar-Ge’si ve CATKIN’in geliştirdiği ürünlerin OEM/ODM üretimi.' },
    ],
    info: [
      { label: 'Şirket', value: 'SOLKERN Co., Ltd.' },
      { label: 'CEO', value: 'Jin-Tae Park' },
      { label: 'Kuruluş', value: 'Ağustos 2026' },
      { label: 'Faaliyet', value: 'Gıda toptan ve perakende · Hammadde Ar-Ge’si · Bilişim (uygulama geliştirme)' },
      { label: 'Adres', value: '5F 505-J341, 10-20 Jungbong-daero 612beon-gil, Seo-gu, Incheon, Güney Kore (Cheongna Plaza)' },
      { label: 'E-posta', value: 'solkern@solkern.kr' },
    ],
    founderQuote: { quote: 'Bugün üretip paketlediğimiz ürünü yarın bir çocuk yiyecek. Belki benim oğlum ya da torunum. Bu yüzden hepimiz ürünü yaparken kendimizi ve çocuklarımızı düşünürüz.', who: 'Valijon Salixov · ERMÁK’ın kurucusu' },
  },
  origin: {
    hero: { eyebrow: 'ORIGIN', title: 'The Land Makes the Ingredient', body: 'Güneş, toprak, iklim ve köklü bir meyvecilik kültürü. İyi ürün, iyi hammaddeyle başlar.' },
    chapters: [
      { num: '01', title: 'Güneş', body: 'Özbekistan, yılın büyük bölümü açık geçen karasal bir iklim kuşağındadır. Uzun ve güçlü güneşlenme, meyvenin rengini ve kokusunu belirleyen en önemli koşuldur.', placeholder: 'ORIGIN-SUN', note: 'Fergana Vadisi’nde bir meyve bahçesinin üzerinde sabah güneşi' },
      { num: '02', title: 'Toprak ve su', body: 'Tanrı Dağları’ndan inen sular ve vaha tarımı geleneği. Kurak bir kıtanın ortasında meyve yetişmesinin nedeni budur.', placeholder: 'ORIGIN-SOIL', note: 'Sulama kanalları ve kızıl toprak' },
      { num: '03', title: 'Meyvecilik kültürü', body: 'İpek Yolu’ndan bu yana aktarılan meyve yetiştirme ve kurutma bilgisi. Kayısı, nar, üzüm ve kavun bu toprakların gündelik hayatı ve kültürüdür.', placeholder: 'ORIGIN-CULTURE', note: 'Damlarda kurutulan kayısılar, pazarda kuruyemiş yığınları' },
      { num: '04', title: 'Üretim', body: 'ERMÁK, 1992’den beri Özbekistan’da doğal gıda üretiyor. Her hammaddenin mevsimine göre sıkıyor, kurutuyor ve kavuruyor.', placeholder: 'ORIGIN-FACTORY', note: 'Temiz üretim hattı, paslanmaz pres ve cam şişe dolumu' },
    ],
    regions: [
      { name: 'Fergana Vadisi', desc: 'Özbekistan’ın en büyük meyve bölgesi. Kayısı, kiraz, nar ve üzüm yetişir.', crops: ['Kayısı', 'Kiraz', 'Nar', 'Üzüm'] },
      { name: 'Taşkent · Cizzak', desc: 'ERMÁK üretim merkezleri. Ayçekirdeği ve kuruyemiş işleme, fermente süt atıştırmalıkları.', crops: ['Ayçekirdeği', 'Kuruyemiş', 'Kurut'] },
      { name: 'Semerkant · Buhara', desc: 'Kuru meyve ve kuruyemiş ticaretinin tarihî merkezleri.', crops: ['Kuru kayısı', 'Kuru üzüm', 'Badem'] },
      { name: 'Türkiye', desc: 'Fındık, incir, kayısı ve nar gibi meyve hammaddeleri ve yan ürünler için ikinci menşe.', crops: ['Fındık', 'İncir', 'Nar', 'Kayısı'] },
    ],
    turkiye: { title: 'İkinci menşeimiz, Türkiye', body: 'Akdeniz ve Anadolu yaylasının meyve hammaddeleri, SOLKERN hammadde işinin ikinci ayağıdır. Özbekistan ve Türkiye kaynaklarını birlikte değerlendirerek mevsim, çeşit ve miktar açısından istikrar sağlıyoruz.', placeholder: 'ORIGIN-TURKIYE' },
    disclaimer: '* Menşe anlatımları genel bölgesel bilgilere dayanır. Üstünlük veya bileşen karşılaştırması gibi test gerektiren ifadeler, ancak analiz verileri sağlandıktan sonra veriye dayalı olarak eklenecektir.',
  },
  ermak: {
    hero: { eyebrow: 'ERMÁK · SINCE 1992', title: 'ERMÁK, The Taste You Trust', body: '1992’den beri üretilen ERMÁK ürünlerini SOLKERN Asya pazarlarına tanıtıyor. “Ermák”, Özbekçede keyif ve hoşça geçen vakit anlamına gelir.' },
    brandStory: {
      title: 'Özbekistan’da sağlıklı atıştırmalığın öncüsü',
      body: '2008’de Özbekistan’da ayçekirdeğini ilk kez fabrikada işleyip paketleyen ve geleneksel fermente süt ürünü kurutu fabrikada üreten marka. Taşkent ve Cizzak tesislerinde 8 kategoride üretim yapar ve meyve suyu markası ASIL’i de yönetir.',
      facts: [
        { value: '1992', label: 'Kuruluş' },
        { value: '850+', label: 'Çalışan' },
        { value: '8', label: 'Ürün kategorisi' },
        { value: '4', label: 'Uluslararası sertifika (ISO 9001·14001·22000·HALAL)' },
      ],
    },
    newProducts: { badge: 'NEW 2026/27', title: 'QOQI · Challpak — The Third State of Fruit', body: 'Ne taze meyve (1.) ne de klasik kuru meyve (2.): üçüncü bir hâl. QOQI, olgun kayısı, Trabzon hurması ve Acve hurması pürelerinin yumuşakça kurutulmasıyla yapılır; Challpak ise kayısı ve kiraz pestilidir. İkisi de 2026/27 kataloğuna yeni eklendi.', cta: 'Meyve atıştırmalıklarını görün' },
    categoriesTitle: 'ERMÁK · ASIL ürün kategorileri',
    categories: ko.ermak.categories.map((c) => ({
      ...c,
      name: ({
        juice: 'Meyve suları · nektarlar', paste: 'Kuruyemiş ezmeleri', jam: 'Reçel · konfitür · sos', seeds: 'Ayçekirdeği · çekirdekler', nuts: 'Kuruyemişler',
        qurt: 'Kurut · fermente süt atıştırmalıkları', bar: 'Doğal kuruyemiş barları', snack: 'Meyve atıştırmalıkları QOQI · Challpak', other: 'Halka kraker · püre',
      } as Record<string, string>)[c.id] || c.en,
      desc: ({
        juice: 'Elma, ayva, nar, elma-pancar, kiraz, kayısı. Doğrudan sıkılmış meyve suları ve meyve nektarları.',
        paste: 'Yer fıstığı, kaju ve susam (tahin) ezmeleri ile hurma konfitürü.',
        jam: 'Nar, üzüm, kiraz, kayısı, hurma ve ayva reçelleri; nar ve kiraz sosları.',
        seeds: 'Siyah ve beyaz ayçekirdeği (tuzlu / tuzsuz / kavrulmuş). Küçük paketten 2 kg büyük boya.',
        nuts: 'Badem, kaju, Antep fıstığı, yer fıstığı, ayçekirdeği içi, kabak çekirdeği, karışık kuruyemiş ve kuruyemiş-kuru meyve karışımı.',
        qurt: 'Orta Asya’nın geleneksel kurutulmuş fermente süt ürünü kurut, biokurut ve kurtoba ile ayran içecekleri.',
        bar: 'Kabak çekirdeği, badem, susam, karışık kuruyemiş, yer fıstığı ve ayçekirdeği barları.',
        snack: '2026/27 yeni ürünleri: kayısı, Trabzon hurması ve Acve hurması pürelerinin yumuşakça kurutulmasıyla yapılan QOQI ile kayısı ve kiraz pestili Challpak. “Meyvenin üçüncü hâli (The Third State of Fruit)”.',
        other: 'Kuru halka krakerler (teşik külçe / suşki, 3 çeşit) ve elma, kayısı, ayva püreleri.',
      } as Record<string, string>)[c.id],
      point: ({
        juice: 'Menşe hikâyesiyle en doğrudan bağlantılı ana kategori',
        paste: 'Doğal sürülebilir ürün konumu · brunch ve fırın B2B',
        jam: 'Yoğurt, brunch, fırın ve yeme-içme B2B’ye genişleyebilir',
        seeds: 'Küçük paket ve büyük boy birlikte · toptan market adayı',
        nuts: 'Pratik sağlıklı atıştırmalık · çevrimiçi test ürünü adayı',
        qurt: 'Güçlü Orta Asya kimliği · tüketiciyi bilgilendirerek tanıtım',
        bar: 'Pratik sağlıklı atıştırmalık · çevrimiçi test ürünü adayı',
        snack: 'Koreli tüketici için en yeni format · 1 numaralı çevrimiçi test ürünü',
        other: 'Yerel karakteri güçlü seri · ikincil veya test serisi',
      } as Record<string, string>)[c.id],
      products: c.products.map((p) => ({
        ...p,
        name: ({
          j1: 'Nar suyu', j2: 'Elma suyu', j3: 'Ayva suyu', j4: 'Kiraz suyu', j5: 'Kayısı nektarı', j6: 'Elma-pancar suyu',
          p1: 'Fıstık ezmesi', p2: 'Kaju ezmesi', p3: 'Susam ezmesi (tahin)', p4: 'Hurma konfitürü',
          m1: 'Nar reçeli', m2: 'Üzüm reçeli', m3: 'Kiraz · kayısı · ayva reçeli', m4: 'Kiraz sosu · nar sosu',
          s1: 'Siyah ayçekirdeği', s2: 'Beyaz ayçekirdeği', s3: 'Kavrulmuş ayçekirdeği, büyük boy',
          n1: 'Badem', n2: 'Kaju', n3: 'Ayçekirdeği içi', n4: 'Karışık kuruyemiş',
          q1: 'Biokurut', q2: 'Kurut (top)', q3: 'Acı biberli kurut', q4: 'Kurtoba', q5: 'Fesleğenli ayran',
          b1: 'Kabak çekirdeği barı', b2: 'Badem barı', b3: 'Susam · ayçekirdeği barı',
          o1: 'Tuzlu halka kraker', o2: 'Stevia ve beyaz susamlı halka kraker', o3: 'Beyaz susam ve çörek otlu halka kraker', o12: 'Meyve püresi', o13: 'Elma püresi', o14: 'Kayısı püresi', o15: 'Ayva püresi',
          o4: 'Kayısı QOQI', o5: 'Trabzon hurması QOQI', o6: 'Acve hurması QOQI', o7: 'Kayısı Challpak (Bargak)', o8: 'Kayısı Challpak (Kantek)', o9: 'Kiraz Challpak', o10: 'QOQI büyük paket (kayısı)', o11: 'Challpak büyük paket (kiraz)',
          n5: 'Tuzlu karışık kuruyemiş', n6: 'Kuruyemiş ve kuru meyve karışımı', n7: 'Tuzlu kabak çekirdeği (kabuklu)', q6: 'Fesleğenli kurut', q8: 'Sert kurut (Toshqurt)', q7: 'Kare fesleğenli kurut',
        } as Record<string, string>)[p.id] || p.name,
        sub: p.sub?.replace('냉압착', 'soğuk sıkım'),
        sizes: p.sizes?.replace(/대용량/g, 'büyük paket'),
      })),
    })),
    korea: {
      title: 'Korea Launch Roadmap', body: 'Kore lansmanı, kanala uygun ürünlerden başlayarak aşamalı ilerler.',
      phases: [
        { phase: 'PHASE 1', items: 'Çekirdek ve kuruyemiş · reçel ve ezme · kuru meyve', channel: 'Resmî çevrimiçi mağaza · küçük paket kanalları' },
        { phase: 'PHASE 2', items: 'ASIL meyve suları (6) · soslar', channel: 'Toptan marketler · yeme-içme ve kafe B2B' },
        { phase: 'PHASE 3', items: 'Kurut · fermente süt içecekleri', channel: 'Hayvansal ürün ithalat koşulları teyit edildikten sonra' },
      ],
    },
    cta: { title: 'Tüm ürün kataloğuna mı ihtiyacınız var?', body: 'ERMÁK 2026/27 ve ASIL kataloglarını ürün bazındaki şartnamelerle birlikte gönderiyoruz.', button: 'Katalog isteyin' },
  },
  materialLab: {
    hero: { eyebrow: 'MATERIAL LAB · PROJECT 2', title: 'Nothing Ends at the Factory', body: 'Üretimden arta kalan kabuk, çekirdek ve posayı yeni gıda ve malzeme değerine dönüştürüyoruz.' },
    thesis: { title: 'En büyük değer tozda değil, “standardize hammadde”dedir', body: 'Eskiden atılan yan ürünleri temiz, homojen ve belgeleriyle birlikte tedarik etmek. SOLKERN MATERIAL LAB değeri yenilikle değil, kalite güvencesi ve tutarlılıkla yaratır.' },
    tracks: [
      { id: 'beauty', title: 'Güzellik malzemeleri', en: 'BEAUTY', body: 'Polifenol standardize nar kabuğu ekstreleri ve meyve çekirdeği ile kabuklarından doğal peeling tozları. Tane boyutuna göre tasarlanarak cilt tipine uygun yoğunluk sunar.', materials: ['Nar kabuğu ekstresi', 'Nar · kiraz · kayısı çekirdeği tozu', 'Ceviz kabuğu · üzüm çekirdeği tozu'], stage: 'Hammadde temini · ilk sipariş sürüyor', placeholder: 'LAB-BEAUTY' },
      { id: 'food', title: 'Gıda malzemeleri', en: 'FOOD', body: 'Meyve ve tahıl tozlarına dayalı RTE/RTD shake’ler ve elma posası lifi. Kullanılabilir hammaddeler önce ürünleşsin diye yeni gıda hammaddesi onay süreci paralel yürütülür.', materials: ['Meyve tozları (nar, kiraz, kayısı, elma…)', 'Tahıl tozları', 'Posa diyet lifi'], stage: 'Reçete geliştirme · fizibilite', placeholder: 'LAB-FOOD' },
      { id: 'ingredient', title: 'Endüstriyel malzemeler', en: 'INGREDIENT', body: 'Ceviz kabuğu ve diğer kuruyemiş yan ürünlerinden elek derecesine göre aşındırıcı ve dolgu malzemeleri. Şartname ve test raporlarıyla B2B hammadde olarak tedarik edilir.', materials: ['Ceviz kabuğu aşındırıcı', 'Kuruyemiş yan ürünü dolgu', 'Standardize tozlar'], stage: 'Kaynak değerlendirmesi', placeholder: 'LAB-INDUSTRY' },
    ],
    process: [
      { step: '01', title: 'Hammadde temini', desc: 'Özbekistan ve Türkiye’den yan ürünler; dondurarak kurutma ve öğütme' },
      { step: '02', title: 'Analiz', desc: 'Bileşen analizi, pestisit kalıntısı ve ağır metal testleri, COA' },
      { step: '03', title: 'Mevzuat incelemesi', desc: 'Gıda kodeksi ve kozmetik hammadde kurallarına göre kullanım kapsamının ön teyidi' },
      { step: '04', title: 'İkincil işleme', desc: 'Kore’de ekstraksiyon, fraksiyonlama, tane boyutu tasarımı, standardizasyon' },
      { step: '05', title: 'Ürünleştirme · B2B', desc: 'Hammadde tedariki, OEM/ODM ürün geliştirme, ortak iş birliği' },
    ],
    principles: [
      { title: 'Önce mevzuat', desc: 'Yatırımdan önce kullanılabilirliği ve onay sürecini teyit ederiz.' },
      { title: 'Veriyle konuşmak', desc: 'Doğrulanmamış etki veya karşılaştırma ifadesi kullanmayız; COA ve şartnameyle teklif veririz.' },
      { title: 'Artık da bir kaynaktır', desc: 'Ekstraksiyondan kalan pektin ve lifi de ek gelir olarak tasarlarız.' },
    ],
    cta: { title: 'Hammadde iş birliği önerin', body: 'Yan ürün tedariki, ortak Ar-Ge, hammadde alımı, OEM/ODM — her tür iş birliğine açığız.', button: 'Hammadde iş birliği' },
  },
  b2b: {
    hero: { eyebrow: 'B2B', title: 'Partner with SOLKERN', body: 'Ürün dağıtımı, hammadde tedariki, OEM/ODM, Kore’de ikincil işleme ve Asya pazarlarında iş birliği.' },
    services: [
      { id: 'dist', title: 'Ürün dağıtımı', desc: 'ERMÁK · ASIL ürünleri için Kore ve Asya’da dağıtım ortaklığı', bullets: ['Toptan marketler ve büyük perakende', 'Çevrimiçi kanal tedariki', 'Yeme-içme, kafe ve fırın B2B', 'Asya’da ülke bazında ortaklar'] },
      { id: 'raw', title: 'Hammadde tedariki', desc: 'Standardize meyve hammaddeleri, tozlar ve yan ürünler', bullets: ['Meyve eti, kabuk ve çekirdek tozları', 'Dondurularak kurutulmuş hammaddeler', 'COA ve şartname dahil', 'MOQ ve teslim süresi görüşülür'] },
      { id: 'oem', title: 'OEM / ODM', desc: 'Kore’de ikincil işlemeyle ürün geliştirme', bullets: ['Shake, sürülebilir ürün gibi gıdalar', 'Peeling ve ekstre gibi güzellik hammaddeleri', 'Ambalaj ve etiket inceleme desteği', 'Küçük pilot üretim görüşülür'] },
      { id: 'sample', title: 'Numune ve belge talebi', desc: 'Ürün numuneleri ve kalite belgeleri', bullets: ['Ürün katalogları (ERMÁK · ASIL)', 'Ürün şartnameleri', 'Analiz sertifikaları (COA) ve belgeler', 'Numune gönderimi görüşülür'] },
    ],
    steps: [
      { step: '01', title: 'Talep', desc: 'İlgilendiğiniz ürünü, kullanım amacını ve miktarı form veya e-posta ile bildirin.' },
      { step: '02', title: 'Belge · numune', desc: 'Katalog, şartname, COA ve numune sağlarız.' },
      { step: '03', title: 'Koşullar', desc: 'Fiyat, MOQ, teslim süresi, Incoterms ve ödeme koşulları görüşülür.' },
      { step: '04', title: 'Sözleşme · tedarik', desc: 'Sözleşmeden sonra ithalat, gümrük ve yurt içi lojistikle teslim edilir.' },
    ],
    docs: ['Ürün kataloğu', 'Ürün şartnameleri (Spec Sheet)', 'Analiz sertifikası (COA)', 'ISO · HALAL sertifikaları', 'Menşe şahadetnamesi', 'Etiket bilgileri'],
    faq: [
      { q: 'Minimum sipariş miktarı (MOQ) nedir?', a: 'Ürüne ve paket boyutuna göre değişir. Hedef miktarınızı iletirseniz ürün bazında MOQ ve teslim süresini bildiririz.' },
      { q: 'Numune alabilir miyim?', a: 'Evet. B2B talebinden sonra numune ürünlerini ve miktarını birlikte belirleriz; kargo ücreti önceden kararlaştırılır.' },
      { q: 'Hammadde (yan ürün) küçük miktarda alınabilir mi?', a: 'Ar-Ge amaçlı küçük numune alımlarını destekliyoruz. Şartname ve test raporlarıyla birlikte sağlanır.' },
      { q: 'Kore dışına da tedarik yapıyor musunuz?', a: 'Evet. ERMÁK dağıtım sözleşmesindeki Asya-Pasifik’in 12 pazarında (Kore, Çin, Japonya, Tayvan, Hong Kong, Moğolistan, Vietnam, Tayland, Malezya, Endonezya, Filipinler, Avustralya) ortaklarla çalışıyoruz. Orta Asya’daki beş ülke doğrudan ERMÁK merkezi tarafından yönetilir.' },
    ],
    cta: { title: 'B2B görüşmenizi şimdi başlatın', button: 'B2B talebi gönderin' },
  },
  news: {
    hero: { eyebrow: 'NEWS', title: 'SOLKERN Journal', body: 'Seyahatler, sözleşmeler, lansmanlar, fuarlar ve Ar-Ge gelişmeleri.' },
    empty: 'Henüz haber yok.',
    items: [
      { id: 'n-2026-09-01', date: '2026.09', category: 'R&D', title: 'İlk 100 kg dondurularak kurutulmuş nar kabuğu tozu sipariş edildi', summary: 'Nar kabuğu ekstresi hammadde işinin ilk adımı olarak 100 kg dondurularak kurutulmuş toz sipariş ettik. Analiz ve standardizasyon çalışmaları başlıyor.', placeholder: 'NEWS-POMEGRANATE' },
      { id: 'n-2026-08-01', date: '2026.08', category: 'COMPANY', title: 'SOLKERN Co., Ltd. kuruldu', summary: 'SOLKERN, Incheon Cheongna’da kuruldu. ERMÁK ürün dağıtımı ve hammadde Ar-Ge’si tam anlamıyla başlıyor.', placeholder: 'NEWS-OFFICE' },
      { id: 'n-2026-06-01', date: '2026.06', category: 'PRODUCT', title: 'ERMÁK · ASIL Korece katalogları yayımlandı', summary: 'ERMÁK’ın 8 kategorisini ve ASIL’in 6 meyve suyu ile 2 sosunu içeren Korece kataloglar yayımlandı.', placeholder: 'NEWS-CATALOG' },
    ],
  },
  contact: {
    hero: { eyebrow: 'CONTACT', title: 'Partner with SOLKERN', body: 'Ürün dağıtımı, hammadde tedariki, OEM/ODM veya Kore ve Asya pazarlarında iş birliği için teklifinizi iletin. İki iş günü içinde yanıtlıyoruz.' },
    form: {
      name: 'Adınız', company: 'Şirket', email: 'E-posta', phone: 'Telefon', country: 'Ülke / bölge',
      type: 'Talep türü', typeOptions: ['Ürün dağıtımı', 'Hammadde tedariki', 'OEM / ODM', 'Numune · katalog talebi', 'Hammadde iş birliği · Ar-Ge', 'Diğer'],
      product: 'İlgilendiğiniz ürün / hammadde', quantity: 'Tahmini miktar · MOQ', message: 'Mesajınız',
      agree: 'Kişisel verilerimin toplanmasını ve kullanılmasını kabul ediyorum (talebi yanıtlamak amacıyla, 1 yıl saklanır)', submit: 'Talebi gönder',
      success: 'Talebiniz alındı', successBody: 'Ekibimiz inceledikten sonra e-posta veya telefonla dönüş yapacaktır.',
      privacy: 'Toplanan veriler: ad, şirket, e-posta, telefon, mesaj · Amaç: talebin yanıtlanması · Saklama süresi: 1 yıl',
    },
    info: ko.contact.info,
    officeTitle: 'OFFICE',
    address: '5F 505-J341, 10-20 Jungbong-daero 612beon-gil, Seo-gu, Incheon, Güney Kore (Cheongna Plaza)',
  },
  territory: {
    eyebrow: 'DISTRIBUTION TERRITORY',
    title: 'Asia-Pacific 12 Markets',
    body: 'ERMÁK dağıtım sözleşmesi kapsamında, Kore merkezli olarak Kuzeydoğu Asya, Güneydoğu Asya ve Okyanusya’daki 12 pazara ERMÁK ürünleri tedarik ediyoruz.',
    countLabel: 'Hak sahibi olunan pazar',
    regions: [
      { name: 'Kuzeydoğu Asya', countries: [
        { code: 'KR', name: 'Kore', city: 'Incheon · merkez' },
        { code: 'CN', name: 'Çin', city: 'Pekin' },
        { code: 'JP', name: 'Japonya', city: 'Tokyo' },
        { code: 'TW', name: 'Tayvan', city: 'Taipei' },
        { code: 'HK', name: 'Hong Kong', city: 'Hong Kong' },
        { code: 'MN', name: 'Moğolistan', city: 'Ulan Batur' },
      ] },
      { name: 'Güneydoğu Asya', countries: [
        { code: 'VN', name: 'Vietnam', city: 'Hanoi' },
        { code: 'TH', name: 'Tayland', city: 'Bangkok' },
        { code: 'MY', name: 'Malezya', city: 'Kuala Lumpur' },
        { code: 'ID', name: 'Endonezya', city: 'Cakarta' },
        { code: 'PH', name: 'Filipinler', city: 'Manila' },
      ] },
      { name: 'Okyanusya', countries: [{ code: 'AU', name: 'Avustralya', city: 'Sidney' }] },
    ],
    origins: [
      { code: 'UZ', name: 'Özbekistan', role: 'ERMÁK üretimi · menşe' },
      { code: 'TR', name: 'Türkiye', role: 'Meyve hammaddeleri · yan ürünler' },
    ],
    hub: 'Merkez',
    legendTerritory: '12 pazar',
    legendOrigin: 'Menşe',
    legendDirect: 'Orta Asya (doğrudan ERMÁK merkezi yönetir)',
    note: '* ERMÁK dağıtım sözleşmesindeki bölgeleri gösterir. Orta Asya’daki beş ülke (Kazakistan, Kırgızistan, Tacikistan, Türkmenistan, Özbekistan) doğrudan ERMÁK merkezi tarafından yönetilir. Ülke bazındaki tedarik koşulları B2B talebiyle bildirilir.',
    tapHint: 'Haritada vurgulamak için bir ülkeye dokunun',
  },
  ui: {
    langName: 'Türkçe',
    sections: { solkernBusiness: 'Üç iş kolu, tek akış', solkernPartners: 'Üretimden satışa üç şirketli yapı', companyInfo: 'Şirket bilgileri', originRegions: 'Hammaddenin yetiştiği yerler', labTracks: 'Üç malzeme alanı', labProcess: 'Yan üründen standardize hammaddeye', b2bServices: 'İş birliği yolları', b2bProcess: 'Talepten tedarike', b2bFaq: 'Sık sorulan sorular' },
    originMarquee: ['Güneş', 'Toprak', 'İklim', 'Meyvecilik kültürü', 'Özbekistan', 'Türkiye', 'Nar', 'Kayısı', 'Kiraz', 'Kuruyemiş'],
    table: { region: 'Bölge', country: 'Ülke', city: 'Başlıca şehir' },
    regionsLabel: 'Bölgeler', originsLabel: 'Menşeler',
    prev: 'Önceki', next: 'Sonraki',
    productNote: '* Ürün özellikleri ve etiket ifadeleri ithalat etiketine göre kesinleşir; katalog talebinde ürün bazında şartname sağlanır.',
    countryPlaceholder: 'Türkiye',
    privacy: {
      title: 'Gizlilik Politikası',
      intro: 'SOLKERN Co., Ltd. (“Şirket”), web sitesi taleplerini karşılamak amacıyla kişisel verileri aşağıdaki şekilde toplar ve kullanır.',
      items: ['Toplanan veriler: ad, şirket, e-posta, telefon, ülke, mesaj', 'Amaç: taleplerin yanıtlanması; teklif, numune ve belge sağlanması', 'Saklama süresi: alındığı tarihten itibaren 1 yıl (mevzuat gereği saklanması gereken hâllerde ilgili süre)', 'Üçüncü kişilere aktarım: yok (mevzuatın gerektirdiği hâller hariç)'],
      officer: 'Kişisel verileri koruma sorumlusu: Jin-Tae Park',
    },
  },
  footer: {
    tagline: 'From Origin to New Value',
    company: 'SOLKERN Co., Ltd.',
    ceo: 'Bilgi yönetimi sorumlusu: Jin-Tae Park',
    regNo: 'Vergi kayıt no. 443-86-03703',
    address: '5F 505-J341, 10-20 Jungbong-daero 612beon-gil, Seo-gu, Incheon, Güney Kore',
    email: 'solkern@solkern.kr',
    tel: '+82-10-4589-1030',
    copyright: '© 2026 SOLKERN Co., Ltd. All rights reserved.',
    links: [
      { label: 'Gizlilik politikası', href: '/privacy' },
      { label: 'Yönetici', href: '/admin' },
    ],
  },
};
