import type { Dict } from './types';
import { ko } from './ko';

// O‘zbekcha matn avtomatik tarjima qoralamasi — e’lon qilishdan oldin ona tili o‘zbek bo‘lgan mutaxassis ko‘rib chiqishi tavsiya etiladi.
export const uz: Dict = {
  meta: {
    title: 'SOLKERN | From Origin to New Value — O‘zbekiston va Turkiyaning tabiiy oziq-ovqatlari hamda xomashyo R&D',
    description:
      'SOLKERN O‘zbekiston va Turkiyaning tabiiy oziq-ovqat brendlari ERMÁK va ASIL mahsulotlarini Osiyo bozorlariga taqdim etadi, meva xomashyosi va qo‘shimcha mahsulotlarini Koreya qayta ishlash texnologiyasi yordamida yangi xomashyoga aylantiradi.',
  },
  nav: ko.nav,
  common: {
    more: 'Batafsil', contact: 'Bog‘lanish', catalog: 'Katalog so‘rash', b2b: 'B2B maslahat',
    viewProducts: 'ERMÁK mahsulotlarini ko‘rish', viewMaterial: 'Xomashyo va B2B', scroll: 'SCROLL', langLabel: 'Til',
    readMore: 'Batafsil o‘qish', back: 'Ro‘yxatga qaytish', send: 'Yuborish', sending: 'Yuborilmoqda…', sent: 'Yuborildi',
    error: 'Yuborib bo‘lmadi. Birozdan so‘ng qayta urinib ko‘ring.', required: 'majburiy', officialDistributor: 'ERMÁK’ning Osiyoga birgalikda chiqish bo‘yicha rasmiy hamkori',
  },
  home: {
    hero: {
      eyebrow: 'Quality Without Borders · ERMÁK’ning Osiyoga birgalikda chiqish bo‘yicha rasmiy hamkori · Xomashyo R&D',
      title: 'From Origin', titleAccent: 'to New Value',
      body: 'O‘zbekiston tabiatida yetishgan mevalar Osiyo dasturxoniga yetib boradi va Koreya texnologiyasi orqali yana bir bor qadriyatga aylanadi.',
      cta1: 'ERMÁK mahsulotlarini ko‘rish', cta2: 'Xomashyo va B2B',
    },
    journey: {
      eyebrow: 'THE SOLKERN WAY',
      title: 'Yaxshi xomashyoni topamiz, bozorini yaratamiz va qolgan qadriyatni ham qayta hayotga qaytaramiz.',
      steps: [
        { key: 'origin', label: '01 ORIGIN', title: 'Xomashyo o‘sadigan zamin', body: 'Kuchli quyosh, kontinental iqlim va qadimiy bog‘dorchilik madaniyati. O‘zbekiston va Turkiyaning mevalari hamda yong‘oqlari hikoyadan boshlanadi.' },
        { key: 'product', label: '02 PRODUCT', title: 'ERMÁK tayyor mahsulotlari', body: '1992-yildan beri ishlab chiqarilayotgan ERMÁK sharbatlari, murabbolari, yong‘oq pastalari, pistalari, qurti va batonchiklarini SOLKERN Osiyo bozoriga taqdim etadi.' },
        { key: 'second', label: '03 SECOND LIFE', title: 'Zavodda tugamaydigan qadriyat', body: 'Ishlab chiqarishdan qolgan po‘st, danak va turp Koreya qayta ishlash texnologiyasi bilan oziq-ovqat, go‘zallik va sanoat xomashyosiga aylanadi.' },
        { key: 'market', label: '04 MARKET', title: 'Osiyo distribyutsiyasi va B2B tarmog‘i', body: 'Tayyor mahsulot distribyutsiyasi, xomashyo yetkazib berish, OEM/ODM. Koreyani markaz qilib, Osiyodagi hamkorlar bilan birga bozor yaratamiz.' },
      ],
    },
    land: {
      eyebrow: '02 · THE LAND', title: 'Why Central Asia, Why Uzbekistan',
      body: 'Kuchli quyosh nuri, kontinental iqlim va asrlar davomidagi bog‘dorchilik madaniyati xilma-xil meva va yong‘oqlarni yetishtiradi. Yaxshi mahsulot yaxshi xomashyodan boshlanadi.',
      facts: [
        { value: '300+', label: 'Yiliga quyoshli kunlar (hudud bo‘yicha taxminiy)' },
        { value: '1992', label: 'ERMÁK tashkil etilgan yil' },
        { value: '2', label: 'Asosiy kelib chiqish joyi — O‘zbekiston · Turkiya' },
        { value: '9', label: 'ERMÁK mahsulot toifasi' },
      ],
      cta: 'Kelib chiqish hikoyasini o‘qish',
    },
    fruit: {
      eyebrow: '03 · THE FRUIT', title: 'One Origin, Many Possibilities',
      body: 'Anor, o‘rik, olcha, olma, uzum, yong‘oqlar. Bitta xomashyo bir vaqtning o‘zida ham tayyor mahsulotga, ham materialga aylanadi.',
      items: [
        { name: 'Anor', product: 'Sharbat · murabbo · sous', material: 'Po‘st ekstrakti · danak kukuni', image: '/images/custom/FRUIT-POMEGRANATE.webp' },
        { name: 'Olma', product: 'Sharbat · pyure', material: 'Olma turpi tolasi', image: '/images/fruits/apple.webp' },
        { name: 'Olcha', product: 'Sharbat · murabbo · sous', material: 'Danakdan skrab kukuni', image: '/images/fruits/cherry.webp' },
        { name: 'O‘rik', product: 'QOQI · Challpak · nektar · murabbo', material: 'Danak va po‘st materiallari', placeholder: 'FRUIT-APRICOT' },
        { name: 'Yong‘oq va urug‘lar', product: 'Yong‘oq pastasi · batonchik · qovurilgan', material: 'Yong‘oq qoldiqlaridan oziq-ovqat xomashyosi', placeholder: 'FRUIT-NUTS' },
        { name: 'Uzum · xurmo', product: 'Murabbo · konfityur', material: 'Uzum danagi · po‘st materiallari', placeholder: 'FRUIT-GRAPE' },
      ],
      cta: 'Meva bo‘yicha imkoniyatlarni ko‘rish',
    },
    collection: { eyebrow: '04 · ERMÁK COLLECTION', title: 'The Taste You Trust', body: 'Sharbat va nektarlar, yong‘oq pastalari, murabbo va souslar, pista va yong‘oqlar, qurt hamda batonchiklar — ERMÁK’ning asosiy mahsulot turlari.', cta: 'Mahsulot katalogini so‘rash' },
    featured: { eyebrow: '05 · FEATURED PRODUCTS', title: 'Korea Launch Priority', body: 'Koreyada sotuvga chiqarish pista va yong‘oqlar, murabbo va pastalar, sharbat, qurt kabi savdo kanaliga mos mahsulotlardan boshlab bosqichma-bosqich amalga oshiriladi.', cta: 'B2B maslahat', tags: ['Onlayn sinov mahsulotlari', 'Ulgurji do‘konlar uchun katta hajm', 'Umumiy ovqatlanish va novvoyxona B2B', 'Kichik qadoq kanallari'] },
    secondLife: {
      eyebrow: '06 · SECOND LIFE', title: 'Nothing Ends at the Factory',
      body: 'Ishlab chiqarish tugadi degani xomashyoning qadri tugadi degani emas. Po‘st, danak va turp Koreya qayta ishlash texnologiyasi bilan yangi materialga aylanadi.',
      flow: [
        { label: 'Zavod qoldiqlari', desc: 'Anor po‘sti · meva danaklari · turp · yong‘oq qoldiqlari' },
        { label: 'Birlamchi qayta ishlash', desc: 'Yuvish · (muzlatib) quritish · maydalash · zarracha o‘lchamini belgilash' },
        { label: 'Koreya R&D', desc: 'Tarkib tahlili · ekstraksiya · standartlashtirish · tahlil sertifikati' },
        { label: 'Yangi materiallar', desc: 'Oziq-ovqat · go‘zallik · sanoat uchun B2B yetkazib berish' },
      ],
      cta: 'MATERIAL LAB’ni ko‘rish',
    },
    material: {
      eyebrow: '07 · MATERIAL VALUE', title: 'Food · Beauty · Ingredient',
      body: 'Olma turpi tolaga, anor po‘sti kosmetik ekstraktga, yong‘oq qoldiqlari oziq-ovqat xomashyosiga aylanishi mumkin.',
      cards: [
        { title: 'FOOD', from: 'Meva va don kukunlari', to: 'RTE/RTD kokteyl · oziq tolasi', desc: 'O‘zbek meva kukunlarini Koreya retsepti asosida mahsulotga aylantirish', placeholder: 'MAT-FOOD' },
        { title: 'BEAUTY', from: 'Anor po‘sti · meva danaklari', to: 'Ekstraktlar · tabiiy skrab kukuni', desc: 'Polifenol bo‘yicha standartlashtirilgan ekstraktlar va zarracha o‘lchami bo‘yicha skrab xomashyosi', placeholder: 'MAT-BEAUTY' },
        { title: 'INGREDIENT', from: 'Turp · yong‘oq po‘chog‘i', to: 'Tola · sanoat materiallari', desc: 'Standartlashtirilgan kukun va to‘liq hujjatlarga ega B2B xomashyo', placeholder: 'MAT-INGREDIENT' },
      ],
      cta: 'Xomashyo bo‘yicha hamkorlik',
    },
    market: {
      eyebrow: '08 · MARKET', title: 'Asia Distribution & B2B Network',
      body: 'SOLKERN Koreyani markaz qilib, ERMÁK tayyor mahsulotlarini Osiyo-Tinch okeani mintaqasidagi 12 bozorga yetkazadi hamda Koreyada ikkilamchi qayta ishlash materiallari biznesini birga olib boradi.',
      nodes: [
        { name: 'UZBEKISTAN', role: 'Xomashyo · ERMÁK ishlab chiqarishi' },
        { name: 'TÜRKİYE', role: 'Meva xomashyosi · qo‘shimcha mahsulotlar' },
        { name: 'KOREA', role: 'SOLKERN R&D · qayta ishlash · distribyutsiya' },
        { name: 'ASIA-PACIFIC 12', role: '12 bozorda tayyor mahsulot va xomashyo B2B' },
      ],
      cta: 'Hamkorlik bo‘yicha murojaat',
    },
    trust: {
      eyebrow: '09 · TRUST', title: 'Data-backed Origin Story',
      body: 'Biz faqat tahlil ma’lumotlari, sertifikatlar, import talablari va sifat hujjatlari bilan tasdiqlangan xomashyo va mahsulotlarni taklif qilamiz.',
      items: [
        { title: 'Tahlil sertifikati (COA)', desc: 'Pestitsid qoldiqlari, og‘ir metallar, mikrobiologiya kabi xavfsizlik sinovlari hisobotlariga asoslangan taklif' },
        { title: 'Import talablarini ko‘rib chiqish', desc: 'Koreya oziq-ovqat kodeksi va import xavfsizligi qoidalari bo‘yicha har bir mahsulotni oldindan tekshirish' },
        { title: 'Yorliqni tekshirish', desc: 'Faqat tasdiqlangan iboralar qo‘llanadi; tasdiqlanmagan iboralar ishlatilmaydi' },
        { title: 'Sertifikatlangan ishlab chiqarish', desc: 'ISO 9001 · ISO 14001 · ISO 22000 (HACCP) · HALAL sertifikatiga ega ishlab chiqaruvchilar' },
      ],
      certs: ['ISO 9001:2015', 'ISO 14001:2015', 'ISO 22000:2018 (HACCP)', 'HALAL UAE.S GSO 2055-1'],
      cta: 'Sifat hujjatlarini so‘rash',
      note: '* Sertifikatlar ERMÁK ishlab chiqaruvchi korxonalariga (ERMAKPLUS LLC · ZAFARHON LLC) tegishli; har bir mahsulot bo‘yicha qo‘llanish doirasi so‘rov asosida tasdiqlanadi.',
    },
    contact: { eyebrow: '10 · CONTACT', title: 'Partner with SOLKERN', body: 'Tayyor mahsulot distribyutsiyasi, xomashyo yetkazib berish, OEM/ODM yoki Koreya va Osiyo bozorlarida hamkorlik bo‘yicha taklifingizni yuboring.', cta1: 'Bog‘lanish', cta2: 'Katalog so‘rash' },
    daily: {
      eyebrow: 'SOLKERN DAILY',
      title: 'Kundalik hayotda ERMÁK',
      body: 'Nonushta dasturxonidan tushdan keyingi bir stakangacha — O‘zbekiston mevalari Koreyadagi bir kunga singib ketadigan lahzalar.',
      captions: ['Ertalab · yeryong‘oq pastali tost', 'Tushdan keyin · bir stakan anor sharbati', 'Choy vaqti · QOQI mevali gazak', 'Branch · yogurt va olcha murabbosi', 'Dam olish kuni · sayr va yong‘oqli batonchik', 'Kafe · ayron va qurt'],
    },
    timeline: {
      eyebrow: 'SINCE 1992',
      title: 'Xomashyo zaminidan Koreya texnologiyasigacha davom etayotgan vaqt',
      items: [
        { year: '1992', title: 'ERMÁK tashkil etildi', desc: 'Tabiiy oziq-ovqat brendi ERMÁK O‘zbekistonning Toshkent shahrida ish boshladi.' },
        { year: '2008', title: 'Pistani zavodda qayta ishlash · qurtni zavodda ishlab chiqarish', desc: 'O‘zbekistonda birinchi bo‘lib pistani zavodda qayta ishlab qadoqladi va an’anaviy qurtni zavodda ishlab chiqara boshladi.' },
        { year: '2025', title: 'ERMÁK uchun Osiyo-Tinch okeanidagi 12 bozor huquqi', desc: 'CATKIN Co., Ltd. ERMÁK tayyor mahsulotlarini Osiyo-Tinch okeani mintaqasidagi 12 bozorda sotish huquqini oldi.' },
        { year: '2026.06', title: 'ERMÁK · ASIL koreys tilidagi katalogi nashr etildi', desc: 'ERMÁK’ning 8 toifasi hamda ASIL’ning 6 turdagi sharbati va 2 turdagi sousini o‘z ichiga olgan koreys tilidagi katalog nashr etildi.' },
        { year: '2026.08', title: 'SOLKERN Co., Ltd. tashkil etildi', desc: 'Incheon shahrining Cheongna hududida tashkil etilgan SOLKERN ERMÁK’ning Osiyoga birgalikda chiqish bo‘yicha rasmiy hamkori sifatida distribyutsiya va xomashyo R&D ishlarini boshladi.' },
        { year: '2026.09', title: 'Anor po‘sti kukuniga birinchi buyurtma', desc: '100 kg muzlatib quritilgan anor po‘sti kukuniga buyurtma berilib, MATERIAL LAB’ning birinchi loyihasi boshlandi.' },
      ],
    },
  },
  solkern: {
    hero: { eyebrow: 'ABOUT SOLKERN', title: 'Yaxshi xomashyoni topamiz, bozorini yaratamiz va qolgan qadriyatni ham qayta hayotga qaytaramiz.', body: 'SOLKERN Co., Ltd. — O‘zbekiston va Turkiyaning tabiiy oziq-ovqatlari hamda meva xomashyosini Koreya va Osiyo bozorlari bilan bog‘laydigan xomashyo, distribyutsiya va R&D kompaniyasi.' },
    statement: 'Origin → Product → Second Life → Market. Markaziy Osiyo xomashyosidan ERMÁK tayyor mahsulotlarigacha va Koreyadagi ikkilamchi qayta ishlash materiallari biznesigacha — yagona oqim.',
    identity: [
      { title: 'ERMÁK’ning Osiyoga birgalikda chiqish bo‘yicha rasmiy hamkori', body: '1992-yildan beri faoliyat yuritayotgan O‘zbekistonning yetakchi tabiiy oziq-ovqat brendi ERMÁK va sharbat brendi ASIL mahsulotlarini Koreya hamda Osiyo-Tinch okeani mintaqasidagi 12 bozorga taqdim etamiz.' },
      { title: 'Xomashyo R&D · Koreyada ikkilamchi qayta ishlash', body: 'Meva xomashyosi va ishlab chiqarish qoldiqlarini (po‘st, danak, turp) tahlil qilib, qayta ishlab va standartlashtirib, oziq-ovqat, go‘zallik va sanoat materiallariga aylantiramiz.' },
      { title: 'Ma’lumotlar bilan mustahkamlangan ishonch', body: 'Tuyg‘u tabiatdan boshlanadi; B2B ishonch esa tahlil sertifikatlari, sertifikatlar va import talablarini ko‘rib chiqish bilan yakunlanadi.' },
    ],
    business: [
      { title: 'Tayyor mahsulot distribyutsiyasi', desc: 'ERMÁK · ASIL mahsulotlarini Koreya va Osiyoda tarqatish', items: ['Rasmiy onlayn brend do‘koni', 'Ulgurji do‘konlar va yirik chakana savdo', 'Umumiy ovqatlanish, novvoyxona va kafe B2B', 'Osiyodagi hamkorlar orqali distribyutsiya'] },
      { title: 'Xomashyo yetkazib berish', desc: 'O‘zbekiston va Turkiyadan meva xomashyosi, kukunlar va qo‘shimcha mahsulotlar', items: ['Meva eti, po‘st va danak kukunlari', 'Muzlatib quritilgan xomashyo', 'Spetsifikatsiya va COA bilan birga', 'MOQ va namunalar kelishiladi'] },
      { title: 'R&D · OEM/ODM', desc: 'Koreyada ikkilamchi qayta ishlash orqali material va mahsulot yaratish', items: ['Tahlil, ekstraksiya, standartlashtirish', 'Yangi oziq-ovqat xomashyosini tan oldirish yo‘nalishi', 'Kosmetik xomashyo va skrab kukunlari', 'OEM/ODM mahsulot ishlab chiqish'] },
    ],
    partners: [
      { name: 'ZAFARXON · ERMÁK', role: 'O‘zbekistonda ishlab chiqarish', desc: 'ERMAKPLUS LLC · ZAFARHON LLC. Toshkent va Jizzaxdagi ishlab chiqarish bazalari, ISO · HACCP · HALAL sertifikatiga ega liniyalar.' },
      { name: 'CATKIN Co., Ltd.', role: 'Import va bojxona hamkori', desc: 'ERMÁK’ning Osiyo-Tinch okeani mintaqasidagi 12 bozor (Koreya, Xitoy, Yaponiya, Tayvan, Gonkong, Mongoliya, Vyetnam, Tailand, Malayziya, Indoneziya, Filippin, Avstraliya) bo‘yicha sotish huquqi egasi. Import, bojxona, karantin va ichki omborga qabul qilishni amalga oshiradi.' },
      { name: 'SOLKERN Co., Ltd.', role: 'Savdo · R&D · OEM/ODM', desc: 'Mahsulotni rejalashtirish, marketing, savdo kanallarini boshqarish, xomashyo R&D hamda CATKIN ishlab chiqqan mahsulotlarni OEM/ODM asosida ishlab chiqarish.' },
    ],
    info: [
      { label: 'Kompaniya', value: 'SOLKERN Co., Ltd.' },
      { label: 'CEO', value: 'Jin-Tae Park' },
      { label: 'Tashkil etilgan', value: '2026-yil avgust' },
      { label: 'Faoliyat', value: 'Oziq-ovqat ulgurji va chakana savdosi · Xomashyo R&D · AT (ilova ishlab chiqish)' },
      { label: 'Manzil', value: '5F 505-J341, 10-20 Jungbong-daero 612beon-gil, Seo-gu, Incheon, Koreya Respublikasi (Cheongna Plaza)' },
      { label: 'E-pochta', value: 'solkern@solkern.kr' },
    ],
    founderQuote: { quote: 'Bugun biz tayyorlab qadoqlagan mahsulotni ertaga bir bola yeydi. Balki u mening o‘g‘lim yoki nevaram bo‘lar. Shuning uchun har birimiz mahsulot tayyorlayotganda o‘zimizni va farzandlarimizni o‘ylaymiz.', who: 'Valijon Salixov · ERMÁK asoschisi' },
  },
  origin: {
    hero: { eyebrow: 'ORIGIN', title: 'The Land Makes the Ingredient', body: 'Quyosh, tuproq, iqlim va qadimiy bog‘dorchilik madaniyati. Yaxshi mahsulot yaxshi xomashyodan boshlanadi.' },
    chapters: [
      { num: '01', title: 'Quyosh', body: 'O‘zbekiston yil davomida ochiq kunlar ko‘p bo‘ladigan kontinental iqlim hududida joylashgan. Uzoq va kuchli quyosh nuri mevaning rangi va hidini belgilaydigan eng muhim shartdir.', placeholder: 'ORIGIN-SUN', note: 'Farg‘ona vodiysidagi bog‘ ustida tong quyoshi' },
      { num: '02', title: 'Tuproq va suv', body: 'Tyanshan tog‘laridan oqib tushadigan suv va voha dehqonchiligi an’anasi. Quruq qit’aning o‘rtasida meva yetishishining sababi shu.', placeholder: 'ORIGIN-SOIL', note: 'Sug‘orish ariqlari va qizg‘ish tuproq' },
      { num: '03', title: 'Bog‘dorchilik madaniyati', body: 'Ipak yo‘li davridan beri davom etib kelayotgan meva yetishtirish va quritish mahorati. O‘rik, anor, uzum va qovun — bu zaminning kundalik hayoti va madaniyati.', placeholder: 'ORIGIN-CULTURE', note: 'Tomda quritilayotgan o‘riklar, bozordagi yong‘oq uyumlari' },
      { num: '04', title: 'Ishlab chiqarish', body: 'ERMÁK 1992-yildan beri O‘zbekistonda tabiiy oziq-ovqat ishlab chiqaradi. Har bir xomashyoning mavsumiga qarab siqadi, quritadi va qovuradi.', placeholder: 'ORIGIN-FACTORY', note: 'Toza ishlab chiqarish liniyasi, zanglamaydigan press va shisha idishga quyish' },
    ],
    regions: [
      { name: 'Farg‘ona vodiysi', desc: 'O‘zbekistonning eng yirik bog‘dorchilik hududi. O‘rik, olcha, anor va uzum yetishadi.', crops: ['O‘rik', 'Olcha', 'Anor', 'Uzum'] },
      { name: 'Toshkent · Jizzax', desc: 'ERMÁK ishlab chiqarish bazalari. Pista va yong‘oqlarni qayta ishlash, sut-qatiq gazaklari.', crops: ['Pista', 'Yong‘oqlar', 'Qurt'] },
      { name: 'Samarqand · Buxoro', desc: 'Quritilgan meva va yong‘oq savdosining qadimiy markazlari.', crops: ['Turshak', 'Mayiz', 'Bodom'] },
      { name: 'Turkiya', desc: 'Funduk, anjir, o‘rik va anor kabi meva xomashyosi hamda qo‘shimcha mahsulotlar uchun ikkinchi kelib chiqish joyi.', crops: ['Funduk', 'Anjir', 'Anor', 'O‘rik'] },
    ],
    turkiye: { title: 'Ikkinchi kelib chiqish joyimiz — Turkiya', body: 'O‘rta yer dengizi va Anadolu yassitog‘ligining meva xomashyosi SOLKERN xomashyo biznesining ikkinchi ustunidir. O‘zbekiston va Turkiya manbalarini birga ko‘rib chiqib, mavsum, nav va hajm bo‘yicha barqarorlikni ta’minlaymiz.', placeholder: 'ORIGIN-TURKIYE' },
    disclaimer: '* Kelib chiqish joyi tavsiflari hududga oid umumiy ma’lumotlarga asoslangan. Ustunlik yoki tarkibni taqqoslash kabi sinov talab qiladigan iboralar faqat tahlil ma’lumotlari olingandan so‘ng qo‘shiladi.',
  },
  ermak: {
    hero: { eyebrow: 'ERMÁK · SINCE 1992', title: 'ERMÁK, The Taste You Trust', body: '1992-yildan beri ishlab chiqarilayotgan ERMÁK mahsulotlarini SOLKERN Osiyo bozorlariga taqdim etadi. “Ermak” o‘zbek tilida ko‘ngilochar mashg‘ulot, maroqli vaqt ma’nosini bildiradi.' },
    brandStory: {
      title: 'O‘zbekistonda sog‘lom gazaklar kashshofi',
      body: '2008-yilda O‘zbekistonda birinchi bo‘lib pistani zavodda qayta ishlab qadoqlagan va an’anaviy sut-qatiq mahsuloti — qurtni zavodda ishlab chiqargan brend. Toshkent va Jizzaxdagi bazalarda 8 toifada mahsulot ishlab chiqaradi hamda ASIL sharbat brendini yuritadi.',
      facts: [
        { value: '1992', label: 'Tashkil etilgan' },
        { value: '850+', label: 'Xodimlar' },
        { value: '8', label: 'Mahsulot toifasi' },
        { value: '4', label: 'Xalqaro sertifikat (ISO 9001·14001·22000·HALAL)' },
      ],
    },
    newProducts: { badge: 'NEW 2026/27', title: 'QOQI · Challpak — The Third State of Fruit', body: 'Yangi meva (1-holat) ham, quritilgan meva (2-holat) ham emas — uchinchi holat. QOQI pishgan o‘rik, xurmo va Ajva xurmosi pyuresini yumshoq quritib tayyorlanadi; Challpak esa o‘rik va olchadan tayyorlangan meva qiyomi yaprog‘idir. Ikkalasi ham 2026/27 katalogiga yangi qo‘shildi.', cta: 'Mevali gazaklarni ko‘rish' },
    categoriesTitle: 'ERMÁK · ASIL mahsulot toifalari',
    categories: ko.ermak.categories.map((c) => ({
      ...c,
      name: ({
        juice: 'Sharbat · nektar', paste: 'Yong‘oq pastalari', jam: 'Murabbo · konfityur · sous', seeds: 'Pista · urug‘lar', nuts: 'Yong‘oqlar',
        qurt: 'Qurt · sut-qatiq gazaklari', bar: 'Tabiiy yong‘oqli batonchiklar', snack: 'Mevali gazaklar QOQI · Challpak', other: 'Teshik kulcha · pyure',
      } as Record<string, string>)[c.id] || c.en,
      desc: ({
        juice: 'Olma, behi, anor, olma-lavlagi, olcha, o‘rik. To‘g‘ridan-to‘g‘ri siqilgan sharbatlar va meva nektarlari.',
        paste: 'Yeryong‘oq, keshyu va kunjut (tahini) pastalari hamda xurmo konfityuri.',
        jam: 'Anor, uzum, olcha, o‘rik, xurmo va behi murabbolari; anor va olcha souslari.',
        seeds: 'Qora va oq pista (tuzli / tuzsiz / qovurilgan). Kichik qadoqdan 2 kg lik katta qadoqqacha.',
        nuts: 'Bodom, keshyu, xandon pista, yeryong‘oq, kungaboqar mag‘zi, qovoq urug‘i, yong‘oq aralashmasi hamda yong‘oq va quritilgan meva aralashmasi.',
        qurt: 'Markaziy Osiyoning an’anaviy quritilgan sut-qatiq mahsuloti — qurt, bioqurt hamda qurtoba va ayron ichimliklari.',
        bar: 'Qovoq urug‘i, bodom, kunjut, aralash yong‘oq, yeryong‘oq va kungaboqar urug‘li batonchiklar.',
        snack: '2026/27 yangi mahsulotlari: o‘rik, xurmo va Ajva xurmosi pyuresini yumshoq quritib tayyorlangan QOQI hamda o‘rik va olchali Challpak. “Mevaning uchinchi holati (The Third State of Fruit)”.',
        other: 'Teshik kulcha (sushki) 3 turi hamda olma, o‘rik va behi pyurelari.',
      } as Record<string, string>)[c.id],
      point: ({
        juice: 'Kelib chiqish hikoyasi bilan eng bevosita bog‘liq asosiy toifa',
        paste: 'Tabiiy surtma mahsulot sifatida · branch va novvoyxona B2B',
        jam: 'Yogurt, branch, novvoyxona va umumiy ovqatlanish B2B',
        seeds: 'Kichik qadoq va katta hajm birga · ulgurji do‘konlar uchun nomzod',
        nuts: 'Qulay sog‘lom gazak · onlayn sinov mahsuloti nomzodi',
        qurt: 'Markaziy Osiyoga xos yorqin toifa · iste’molchini tanishtirib kiritish',
        bar: 'Qulay sog‘lom gazak · onlayn sinov mahsuloti nomzodi',
        snack: 'Koreyalik iste’molchi uchun eng yangi format · 1-raqamli onlayn sinov mahsuloti',
        other: 'Mahalliy o‘ziga xosligi kuchli qator · ikkinchi bosqich yoki sinov qatori',
      } as Record<string, string>)[c.id],
      products: c.products.map((p) => ({
        ...p,
        name: ({
          j1: 'Anor sharbati', j2: 'Olma sharbati', j3: 'Behi sharbati', j4: 'Olcha sharbati', j5: 'O‘rik nektari', j6: 'Olma-lavlagi sharbati',
          p1: 'Yeryong‘oq pastasi', p2: 'Keshyu pastasi', p3: 'Kunjut pastasi (tahini)', p4: 'Xurmo konfityuri',
          m1: 'Anor murabbosi', m2: 'Uzum murabbosi', m3: 'Olcha · o‘rik · behi murabbosi', m4: 'Olcha sousi · anor sousi',
          s1: 'Qora pista', s2: 'Oq pista', s3: 'Qovurilgan pista, katta qadoq',
          n1: 'Bodom', n2: 'Keshyu', n3: 'Pista mag‘zi', n4: 'Yong‘oq aralashmasi',
          q1: 'Bioqurt', q2: 'Qurt (dumaloq)', q3: 'Achchiq qurt', q4: 'Qurtoba', q5: 'Rayhonli ayron',
          b1: 'Qovoq urug‘li batonchik', b2: 'Bodomli batonchik', b3: 'Kunjut · kungaboqar urug‘li batonchik',
          o1: 'Tuzli teshik kulcha', o2: 'Steviya va oq kunjutli teshik kulcha', o3: 'Oq kunjut va qora sedanali teshik kulcha', o12: 'Meva pyuresi', o13: 'Olma pyuresi', o14: 'O‘rik pyuresi', o15: 'Behi pyuresi',
          o4: 'O‘rik QOQI', o5: 'Xurmo QOQI', o6: 'Ajva xurmosi QOQI', o7: 'O‘rik Challpak (Bargak)', o8: 'O‘rik Challpak (Kantek)', o9: 'Olcha Challpak', o10: 'QOQI katta qadoq (o‘rik)', o11: 'Challpak katta qadoq (olcha)',
          n5: 'Tuzli yong‘oq aralashmasi', n6: 'Yong‘oq va quritilgan meva aralashmasi', n7: 'Tuzli qovoq urug‘i (po‘chog‘i bilan)', q6: 'Rayhonli qurt', q8: 'Toshqurt', q7: 'To‘rtburchak rayhonli qurt',
        } as Record<string, string>)[p.id] || p.name,
        sub: p.sub?.replace('냉압착', 'sovuq siqilgan'),
        sizes: p.sizes?.replace(/대용량/g, 'katta qadoq'),
      })),
    })),
    korea: {
      title: 'Korea Launch Roadmap', body: 'Koreyada sotuvga chiqarish savdo kanaliga mos mahsulotlardan boshlab bosqichma-bosqich amalga oshiriladi.',
      phases: [
        { phase: 'PHASE 1', items: 'Pista va yong‘oqlar · murabbo va pastalar · quritilgan mevalar', channel: 'Rasmiy onlayn brend do‘koni · kichik qadoq kanallari' },
        { phase: 'PHASE 2', items: 'ASIL sharbatlari (6 tur) · souslar', channel: 'Ulgurji do‘konlar · umumiy ovqatlanish va kafe B2B' },
        { phase: 'PHASE 3', items: 'Qurt · sut-qatiq ichimliklari', channel: 'Chorvachilik mahsulotlari importi talablari tasdiqlangandan so‘ng' },
      ],
    },
    cta: { title: 'To‘liq mahsulot katalogi kerakmi?', body: 'ERMÁK 2026/27 va ASIL kataloglarini har bir mahsulot spetsifikatsiyasi bilan birga yuboramiz.', button: 'Katalog so‘rash' },
  },
  materialLab: {
    hero: { eyebrow: 'MATERIAL LAB · PROJECT 2', title: 'Nothing Ends at the Factory', body: 'Ishlab chiqarishdan qolgan po‘st, danak va turpni yangi oziq-ovqat va material qadriyatiga aylantiramiz.' },
    thesis: { title: 'Eng katta qadriyat kukunda emas, “standartlashtirilgan xomashyo”da', body: 'Ilgari tashlab yuborilgan qoldiqlarni toza, bir xil sifatda va hujjatlari bilan yetkazib berish. SOLKERN MATERIAL LAB qadriyatni yangilik bilan emas, sifat kafolati va barqarorlik bilan yaratadi.' },
    tracks: [
      { id: 'beauty', title: 'Go‘zallik materiallari', en: 'BEAUTY', body: 'Polifenol bo‘yicha standartlashtirilgan anor po‘sti ekstraktlari hamda meva danagi va po‘stidan tabiiy skrab kukunlari. Zarracha o‘lchami bo‘yicha ishlab chiqilib, teri turiga mos kuchni taklif qiladi.', materials: ['Anor po‘sti ekstrakti', 'Anor · olcha · o‘rik danagi kukuni', 'Yong‘oq po‘chog‘i · uzum danagi kukuni'], stage: 'Xomashyo ta’minoti · birinchi buyurtma jarayonda', placeholder: 'LAB-BEAUTY' },
      { id: 'food', title: 'Oziq-ovqat materiallari', en: 'FOOD', body: 'Meva va don kukunlari asosidagi RTE/RTD kokteyllar hamda olma turpi tolasi. Foydalanish mumkin bo‘lgan xomashyo avval mahsulotga aylanishi uchun yangi oziq-ovqat xomashyosini tan oldirish yo‘nalishi parallel olib boriladi.', materials: ['Meva kukunlari (anor, olcha, o‘rik, olma va b.)', 'Don kukunlari', 'Turpdan oziq tolasi'], stage: 'Retsept ishlab chiqish · maqsadga muvofiqlikni o‘rganish', placeholder: 'LAB-FOOD' },
      { id: 'ingredient', title: 'Sanoat materiallari', en: 'INGREDIENT', body: 'Yong‘oq po‘chog‘i va boshqa yong‘oq qoldiqlaridan elak darajasi bo‘yicha abraziv va to‘ldiruvchi materiallar. Spetsifikatsiya va sinov hisobotlari bilan B2B xomashyo sifatida yetkazib beriladi.', materials: ['Yong‘oq po‘chog‘idan abraziv', 'Yong‘oq qoldiqlaridan to‘ldiruvchi', 'Standartlashtirilgan kukunlar'], stage: 'Manbalarni o‘rganish', placeholder: 'LAB-INDUSTRY' },
    ],
    process: [
      { step: '01', title: 'Xomashyo ta’minoti', desc: 'O‘zbekiston va Turkiyadan qoldiqlar; muzlatib quritish va maydalash' },
      { step: '02', title: 'Tahlil', desc: 'Tarkib tahlili, pestitsid qoldiqlari va og‘ir metallar sinovi, COA' },
      { step: '03', title: 'Me’yoriy talablarni ko‘rib chiqish', desc: 'Oziq-ovqat kodeksi va kosmetik xomashyo qoidalari bo‘yicha foydalanish doirasini oldindan aniqlash' },
      { step: '04', title: 'Ikkilamchi qayta ishlash', desc: 'Koreyada ekstraksiya, fraksiyalash, zarracha o‘lchamini belgilash, standartlashtirish' },
      { step: '05', title: 'Mahsulotga aylantirish · B2B', desc: 'Xomashyo yetkazib berish, OEM/ODM mahsulot ishlab chiqish, hamkorlik' },
    ],
    principles: [
      { title: 'Avval me’yoriy talablar', desc: 'Sarmoya kiritishdan oldin foydalanish mumkinligi va tan oldirish yo‘lini aniqlaymiz.' },
      { title: 'Ma’lumotlar bilan gapirish', desc: 'Tasdiqlanmagan samara yoki taqqoslash iboralarini ishlatmaymiz; COA va spetsifikatsiya bilan taklif qilamiz.' },
      { title: 'Qoldiq ham resurs', desc: 'Ekstraksiyadan qolgan pektin va tolani ham qo‘shimcha daromad manbai sifatida rejalashtiramiz.' },
    ],
    cta: { title: 'Xomashyo bo‘yicha hamkorlikni taklif qiling', body: 'Qoldiqlarni yetkazib berish, qo‘shma R&D, xomashyo xaridi, OEM/ODM — har qanday shakldagi hamkorlikka ochiqmiz.', button: 'Xomashyo bo‘yicha murojaat' },
  },
  b2b: {
    hero: { eyebrow: 'B2B', title: 'Partner with SOLKERN', body: 'Tayyor mahsulot distribyutsiyasi, xomashyo yetkazib berish, OEM/ODM, Koreyada ikkilamchi qayta ishlash va Osiyo bozorlarida hamkorlik.' },
    services: [
      { id: 'dist', title: 'Tayyor mahsulot distribyutsiyasi', desc: 'ERMÁK · ASIL mahsulotlari bo‘yicha Koreya va Osiyoda distribyutsiya hamkorligi', bullets: ['Ulgurji do‘konlar va yirik chakana savdo', 'Onlayn kanallarga yetkazib berish', 'Umumiy ovqatlanish, kafe va novvoyxona B2B', 'Osiyo mamlakatlari bo‘yicha hamkorlar'] },
      { id: 'raw', title: 'Xomashyo yetkazib berish', desc: 'Standartlashtirilgan meva xomashyosi, kukunlar va qo‘shimcha mahsulotlar', bullets: ['Meva eti, po‘st va danak kukunlari', 'Muzlatib quritilgan xomashyo', 'COA va spetsifikatsiya bilan', 'MOQ va yetkazish muddati kelishiladi'] },
      { id: 'oem', title: 'OEM / ODM', desc: 'Koreyada ikkilamchi qayta ishlash orqali mahsulot ishlab chiqish', bullets: ['Kokteyl, surtma kabi oziq-ovqat mahsulotlari', 'Skrab va ekstrakt kabi go‘zallik xomashyosi', 'Qadoq va yorliqni ko‘rib chiqishda yordam', 'Kichik sinov partiyasi kelishiladi'] },
      { id: 'sample', title: 'Namuna va hujjatlar so‘rovi', desc: 'Mahsulot namunalari va sifat hujjatlari', bullets: ['Mahsulot kataloglari (ERMÁK · ASIL)', 'Mahsulot spetsifikatsiyalari', 'Tahlil sertifikatlari (COA) va sertifikatlar', 'Namuna jo‘natish kelishiladi'] },
    ],
    steps: [
      { step: '01', title: 'Murojaat', desc: 'Qiziqtirgan mahsulot, foydalanish maqsadi va miqdorni forma yoki e-pochta orqali yuboring.' },
      { step: '02', title: 'Hujjatlar · namunalar', desc: 'Katalog, spetsifikatsiya, COA va namunalarni taqdim etamiz.' },
      { step: '03', title: 'Shartlarni kelishish', desc: 'Narx, MOQ, yetkazish muddati, Incoterms va to‘lov shartlari kelishiladi.' },
      { step: '04', title: 'Shartnoma · yetkazib berish', desc: 'Shartnoma tuzilgach, import, bojxona va ichki logistika orqali yetkazib beriladi.' },
    ],
    docs: ['Mahsulot katalogi', 'Mahsulot spetsifikatsiyalari (Spec Sheet)', 'Tahlil sertifikati (COA)', 'ISO · HALAL sertifikatlari', 'Kelib chiqish sertifikati', 'Yorliq ma’lumotlari'],
    faq: [
      { q: 'Minimal buyurtma miqdori (MOQ) qancha?', a: 'Mahsulot va qadoq o‘lchamiga qarab farq qiladi. Mo‘ljallangan miqdorni bildirsangiz, mahsulot bo‘yicha MOQ va yetkazish muddatini ma’lum qilamiz.' },
      { q: 'Namuna olish mumkinmi?', a: 'Ha. B2B murojaatidan so‘ng namuna turi va miqdorini kelishamiz; yetkazish xarajati oldindan kelishiladi.' },
      { q: 'Xomashyoni (qoldiqlarni) kichik hajmda sotib olish mumkinmi?', a: 'R&D maqsadidagi kichik namuna xaridini qo‘llab-quvvatlaymiz. Spetsifikatsiya va sinov hisobotlari bilan birga taqdim etiladi.' },
      { q: 'Koreyadan tashqariga ham yetkazib berasizmi?', a: 'Ha. ERMÁK distribyutsiya shartnomasidagi Osiyo-Tinch okeani mintaqasining 12 bozorida (Koreya, Xitoy, Yaponiya, Tayvan, Gonkong, Mongoliya, Vyetnam, Tailand, Malayziya, Indoneziya, Filippin, Avstraliya) hamkorlar bilan ishlaymiz. Markaziy Osiyoning besh davlatini ERMÁK bosh ofisi bevosita boshqaradi.' },
    ],
    cta: { title: 'B2B muloqotni hozir boshlang', button: 'B2B murojaat yuborish' },
  },
  news: {
    hero: { eyebrow: 'NEWS', title: 'SOLKERN Journal', body: 'Xizmat safarlari, shartnomalar, yangi mahsulotlar, ko‘rgazmalar va R&D jarayoni haqidagi yangiliklar.' },
    empty: 'Hozircha yangiliklar yo‘q.',
    items: [
      { id: 'n-2026-09-01', date: '2026.09', category: 'R&D', title: 'Birinchi 100 kg muzlatib quritilgan anor po‘sti kukuniga buyurtma berildi', summary: 'Anor po‘sti ekstrakti xomashyo biznesining birinchi bosqichi sifatida 100 kg muzlatib quritilgan kukunga buyurtma berdik. Tahlil va standartlashtirish ishlari boshlanadi.', placeholder: 'NEWS-POMEGRANATE' },
      { id: 'n-2026-08-01', date: '2026.08', category: 'COMPANY', title: 'SOLKERN Co., Ltd. tashkil etildi', summary: 'SOLKERN Incheon shahrining Cheongna hududida tashkil etildi. ERMÁK mahsulotlari distribyutsiyasi va xomashyo R&D ishlari to‘laqonli boshlanadi.', placeholder: 'NEWS-OFFICE' },
      { id: 'n-2026-06-01', date: '2026.06', category: 'PRODUCT', title: 'ERMÁK · ASIL koreys tilidagi kataloglari nashr etildi', summary: 'ERMÁK’ning 8 toifasi hamda ASIL’ning 6 turdagi sharbati va 2 turdagi sousini o‘z ichiga olgan koreys tilidagi kataloglar nashr etildi.', placeholder: 'NEWS-CATALOG' },
    ],
  },
  contact: {
    hero: { eyebrow: 'CONTACT', title: 'Partner with SOLKERN', body: 'Tayyor mahsulot distribyutsiyasi, xomashyo yetkazib berish, OEM/ODM yoki Koreya va Osiyo bozorlarida hamkorlik bo‘yicha taklifingizni yuboring. Ikki ish kuni ichida javob beramiz.' },
    form: {
      name: 'Ismingiz', company: 'Kompaniya', email: 'E-pochta', phone: 'Telefon', country: 'Mamlakat / hudud',
      type: 'Murojaat turi', typeOptions: ['Tayyor mahsulot distribyutsiyasi', 'Xomashyo yetkazib berish', 'OEM / ODM', 'Namuna · katalog so‘rovi', 'Xomashyo bo‘yicha hamkorlik · R&D', 'Boshqa'],
      product: 'Qiziqtirgan mahsulot / xomashyo', quantity: 'Taxminiy miqdor · MOQ', message: 'Xabar matni',
      agree: 'Shaxsiy ma’lumotlarimni to‘plash va ulardan foydalanishga roziman (murojaatga javob berish maqsadida, 1 yil saqlanadi)', submit: 'Murojaatni yuborish',
      success: 'Murojaatingiz qabul qilindi', successBody: 'Mas’ul xodim ko‘rib chiqib, e-pochta yoki telefon orqali javob beradi.',
      privacy: 'To‘planadigan ma’lumotlar: ism, kompaniya, e-pochta, telefon, xabar matni · Maqsad: murojaatga javob berish · Saqlash muddati: 1 yil',
    },
    info: ko.contact.info,
    officeTitle: 'OFFICE',
    address: '5F 505-J341, 10-20 Jungbong-daero 612beon-gil, Seo-gu, Incheon, Koreya Respublikasi (Cheongna Plaza)',
  },
  territory: {
    eyebrow: 'DISTRIBUTION TERRITORY',
    title: 'Asia-Pacific 12 Markets',
    body: 'ERMÁK distribyutsiya shartnomasiga muvofiq, Koreyani markaz qilib, Shimoli-sharqiy Osiyo, Janubi-sharqiy Osiyo va Okeaniyadagi 12 bozorga ERMÁK tayyor mahsulotlarini yetkazamiz.',
    countLabel: 'Sotish huquqiga ega bozorlar',
    regions: [
      { name: 'Shimoli-sharqiy Osiyo', countries: [
        { code: 'KR', name: 'Koreya', city: 'Incheon · markaz' },
        { code: 'CN', name: 'Xitoy', city: 'Pekin' },
        { code: 'JP', name: 'Yaponiya', city: 'Tokio' },
        { code: 'TW', name: 'Tayvan', city: 'Taypey' },
        { code: 'HK', name: 'Gonkong', city: 'Gonkong' },
        { code: 'MN', name: 'Mongoliya', city: 'Ulan-Bator' },
      ] },
      { name: 'Janubi-sharqiy Osiyo', countries: [
        { code: 'VN', name: 'Vyetnam', city: 'Xanoy' },
        { code: 'TH', name: 'Tailand', city: 'Bangkok' },
        { code: 'MY', name: 'Malayziya', city: 'Kuala-Lumpur' },
        { code: 'ID', name: 'Indoneziya', city: 'Jakarta' },
        { code: 'PH', name: 'Filippin', city: 'Manila' },
      ] },
      { name: 'Okeaniya', countries: [{ code: 'AU', name: 'Avstraliya', city: 'Sidney' }] },
    ],
    origins: [
      { code: 'UZ', name: 'O‘zbekiston', role: 'ERMÁK ishlab chiqarishi · kelib chiqish joyi' },
      { code: 'TR', name: 'Turkiya', role: 'Meva xomashyosi · qo‘shimcha mahsulotlar' },
    ],
    hub: 'Markaz',
    legendTerritory: '12 bozor',
    legendOrigin: 'Kelib chiqish joyi',
    legendDirect: 'Markaziy Osiyo (ERMÁK bosh ofisi bevosita boshqaradi)',
    note: '* ERMÁK distribyutsiya shartnomasidagi hududlar ko‘rsatilgan. Markaziy Osiyoning besh davlatini (Qozog‘iston, Qirg‘iziston, Tojikiston, Turkmaniston, O‘zbekiston) ERMÁK bosh ofisi bevosita boshqaradi. Mamlakatlar bo‘yicha yetkazib berish shartlari B2B murojaati orqali ma’lum qilinadi.',
    tapHint: 'Xaritada ajratib ko‘rsatish uchun mamlakatni bosing',
  },
  ui: {
    langName: 'O‘zbekcha',
    sections: { solkernBusiness: 'Uch biznes, yagona oqim', solkernPartners: 'Ishlab chiqarishdan savdogacha — uch kompaniya hamkorligi', companyInfo: 'Kompaniya haqida ma’lumot', originRegions: 'Xomashyo o‘sadigan joylar', labTracks: 'Uch material yo‘nalishi', labProcess: 'Qoldiqdan standart xomashyogacha', b2bServices: 'Hamkorlik usullari', b2bProcess: 'Murojaatdan yetkazib berishgacha', b2bFaq: 'Ko‘p beriladigan savollar' },
    originMarquee: ['Quyosh', 'Tuproq', 'Iqlim', 'Bog‘dorchilik madaniyati', 'O‘zbekiston', 'Turkiya', 'Anor', 'O‘rik', 'Olcha', 'Yong‘oqlar'],
    table: { region: 'Hudud', country: 'Mamlakat', city: 'Asosiy shahar' },
    regionsLabel: 'Hududlar', originsLabel: 'Kelib chiqish joylari',
    prev: 'Oldingi', next: 'Keyingi',
    productNote: '* Mahsulot xususiyatlari va yorliqdagi ma’lumotlar import yorlig‘i asosida yakuniy belgilanadi; katalog so‘ralganda har bir mahsulot spetsifikatsiyasi taqdim etiladi.',
    countryPlaceholder: 'O‘zbekiston',
    privacy: {
      title: 'Maxfiylik siyosati',
      intro: 'SOLKERN Co., Ltd. (keyingi o‘rinlarda “Kompaniya”) veb-sayt orqali kelgan murojaatlarni ko‘rib chiqish uchun shaxsiy ma’lumotlarni quyidagi tartibda to‘playdi va ulardan foydalanadi.',
      items: ['To‘planadigan ma’lumotlar: ism, kompaniya, e-pochta, telefon, mamlakat, xabar matni', 'Maqsad: murojaatga javob berish; narx taklifi, namuna va hujjatlarni taqdim etish', 'Saqlash muddati: qabul qilingan kundan boshlab 1 yil (qonunchilikda saqlash talab etilgan hollarda — tegishli muddat)', 'Uchinchi shaxslarga berish: yo‘q (qonunchilikda nazarda tutilgan hollar bundan mustasno)'],
      officer: 'Shaxsiy ma’lumotlarni himoya qilish bo‘yicha mas’ul: Jin-Tae Park',
    },
  },
  footer: {
    tagline: 'From Origin to New Value',
    company: 'SOLKERN Co., Ltd.',
    ceo: 'Axborot boshqaruvi bo‘yicha mas’ul: Jin-Tae Park',
    regNo: 'Tadbirkorlik subyekti ro‘yxat raqami 443-86-03703',
    address: '5F 505-J341, 10-20 Jungbong-daero 612beon-gil, Seo-gu, Incheon, Koreya Respublikasi',
    email: 'solkern@solkern.kr',
    tel: '+82-10-4589-1030',
    copyright: '© 2026 SOLKERN Co., Ltd. All rights reserved.',
    links: [
      { label: 'Maxfiylik siyosati', href: '/privacy' },
      { label: 'Administrator', href: '/admin' },
    ],
  },
};
